// © 2026 Eric G. Suchanek, PhD — Flux-Frontiers · SPDX-License-Identifier: Elastic-2.0
//
// A conversation as a Markdown document: the questions, the answers, and the
// passages the answers were drawn from.
//
// The passages are the point. An answer lifted out of this app without its
// evidence is just a paragraph of unattributed prose about a book -- exactly
// the thing the whole project exists to avoid -- so every quoted passage
// carries its work, author and score, and the export says which engine wrote
// the answer and what corpus it was asked against.
//
// Pure and separately testable: rendering is where a format quietly loses a
// field, and a view cannot be asked what it produced.

import Foundation
import GutenbergKGKit

enum ConversationMarkdown {

    /// How many passages to quote per answer.
    ///
    /// A turn can carry 25 hits, most of which the model never saw. Quoting
    /// all of them would bury the answer in an export meant to be read;
    /// `SynthesisMetrics.passagesUsed` says how many actually reached the
    /// model, and the header records the rest by count.
    static let quotedPassages = 5

    /// Render a whole conversation.
    ///
    /// :param conversation: The chat to render.
    /// :param dateStyle: Formatter for the header date, injectable so a test
    ///     is not at the mercy of the machine's locale.
    /// :returns: A Markdown document.
    static func render(
        _ conversation: Conversation,
        dateStyle: Date.FormatStyle = .dateTime.year().month().day()
    ) -> String {
        var lines: [String] = [
            "# \(conversation.title)",
            "",
            "*The Knowledge Press -- \(conversation.createdAt.formatted(dateStyle))*",
            "",
        ]

        for turn in conversation.turns {
            lines.append(contentsOf: render(turn))
        }

        lines.append("---")
        lines.append("")
        lines.append(
            "Generated by The Knowledge Press. Passages are from public-domain texts; "
                + "scores are the retrieval engine's own.")
        return lines.joined(separator: "\n")
    }

    /// Render one exchange: question, provenance, answer, then the sources.
    private static func render(_ turn: ChatTurn) -> [String] {
        var lines = ["## \(turn.question)", ""]

        var provenance = ["scope: `\(turn.corpus)`", "engine: \(turn.engine.label)"]
        if let model = turn.metrics?.model { provenance.append(model) }
        lines.append("*\(provenance.joined(separator: " -- "))*")
        lines.append("")

        if !turn.answer.isEmpty {
            lines.append(turn.answer)
        } else if let failure = turn.synthesisFailure {
            // Say what happened rather than leaving a blank section: a chat
            // that was stopped, or that no passage could answer, is a true
            // part of the record.
            lines.append("> \(failure.displayMessage)")
        } else if let error = turn.errorMessage {
            lines.append("> \(error)")
        } else if turn.engine == .off {
            lines.append("> Answer generation was off; the passages follow.")
        }
        lines.append("")

        let hits = turn.retrieval?.hits ?? []
        if !hits.isEmpty {
            lines.append(contentsOf: renderSources(hits, metrics: turn.metrics))
        }
        return lines
    }

    private static func renderSources(_ hits: [Hit], metrics: SynthesisMetrics?) -> [String] {
        let quoted = hits.prefix(quotedPassages)
        var heading = "**Sources** (\(hits.count) retrieved"
        if let used = metrics?.passagesUsed, used < hits.count {
            // The honest number: the context budget is small enough that
            // "25 passages" would overstate what the answer rests on.
            heading += ", \(used) reached the model"
        }
        if hits.count > quoted.count {
            heading += "; \(quoted.count) quoted"
        }
        heading += ")"

        var lines = [heading, ""]
        for hit in quoted {
            let work = hit.title ?? hit.name
            var attribution = work
            if let author = hit.author, !author.isEmpty { attribution += " -- \(author)" }
            lines.append(
                "- **\(attribution)** (\(hit.genre ?? hit.kgName), score \(score(hit.score)))")
            if let text = passage(hit) {
                lines.append("  > \(text)")
            }
        }
        lines.append("")
        return lines
    }

    /// A hit's text, trimmed to something quotable and kept on one line so it
    /// survives as a Markdown blockquote.
    private static func passage(_ hit: Hit, limit: Int = 400) -> String? {
        let raw = (hit.content?.isEmpty == false ? hit.content : hit.summary) ?? ""
        let text = raw.split(whereSeparator: \.isNewline)
            .joined(separator: " ")
            .trimmingCharacters(in: .whitespacesAndNewlines)
        guard !text.isEmpty else { return nil }
        guard text.count > limit else { return text }

        let cut = text.prefix(limit)
        guard let lastSpace = cut.lastIndex(of: " ") else { return cut + "..." }
        return cut[..<lastSpace] + "..."
    }

    private static func score(_ value: Double) -> String {
        String(format: "%.3f", value)
    }

    /// A filename for the exported document, safe on every filesystem the
    /// share sheet might hand it to.
    static func filename(for conversation: Conversation) -> String {
        let stem = conversation.title
            .components(separatedBy: CharacterSet.alphanumerics.inverted)
            .filter { !$0.isEmpty }
            .joined(separator: "-")
            .prefix(60)
        return stem.isEmpty ? "conversation.md" : "\(stem).md"
    }
}
