// © 2026 Eric G. Suchanek, PhD — Flux-Frontiers · SPDX-License-Identifier: Elastic-2.0
//
// The parity gate: does the Swift query path return what the packs' own
// reference implementation returned?
//
// Everything else in this suite tests a piece. This tests the whole path
// against `golden.json`, which `gutenkg export-swift` generated by running the
// Python reference over the same packs. A divergence here is real, and the
// unit tests above say where it is: the tokenizer, or the quantisation.
//
// Needs a built corpus, so it is opt-in:
//
//     GUTENBERG_PACKS=bundles/gutenberg-all/swift swift test
//
// Without that variable every test here is skipped rather than failed — CI has
// no gigabyte of corpus and should not pretend otherwise.

import Foundation
import Testing

@testable import GutenbergKGKit

/// `golden.json`, as the exporter writes it.
private struct GoldenFile: Decodable {
    struct Tolerance: Decodable {
        let rankOverlap: Double
        let scoreDelta: Double
        /// How far a shared hit may move between the reference and here.
        /// Defaulted so a golden file written before this key still loads.
        let maxRankDrift: Int

        enum CodingKeys: String, CodingKey {
            case rankOverlap = "rank_overlap"
            case scoreDelta = "score_delta"
            case maxRankDrift = "max_rank_drift"
        }

        init(from decoder: Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            rankOverlap = try container.decode(Double.self, forKey: .rankOverlap)
            scoreDelta = try container.decode(Double.self, forKey: .scoreDelta)
            maxRankDrift = try container.decodeIfPresent(Int.self, forKey: .maxRankDrift) ?? 2
        }
    }

    struct Entry: Decodable {
        struct Hit: Decodable {
            let rank: Int
            let nodeID: String
            let score: Double

            enum CodingKeys: String, CodingKey {
                case rank, score
                case nodeID = "node_id"
            }
        }

        let query: String
        let packs: [String: [Hit]]
    }

    let k: Int
    let embedModel: String
    let tolerance: Tolerance
    let queries: [Entry]

    enum CodingKeys: String, CodingKey {
        case k, tolerance, queries
        case embedModel = "embed_model"
    }
}

private var packsDirectory: URL? {
    guard let path = ProcessInfo.processInfo.environment["GUTENBERG_PACKS"], !path.isEmpty
    else { return nil }
    return URL(fileURLWithPath: (path as NSString).expandingTildeInPath, isDirectory: true)
}

private let corpusInstalled = packsDirectory != nil

@Suite(.enabled(if: corpusInstalled, "set GUTENBERG_PACKS to a built corpus"))
struct GoldenParityTests {

    /// Which corpus scope answers for each pack name in the golden file.
    /// `gutenberg` and `diary` select packs, so each side is a clean 1:1
    /// against the reference, which searched one pack at a time.
    private static let scopes = ["gutenberg": "gutenberg", "diaries": "diary"]

    private func load() throws -> (CorpusPacks, GoldenFile) {
        let directory = try #require(packsDirectory)
        let packs = try CorpusPacks(directory: directory)
        let data = try Data(contentsOf: directory.appendingPathComponent("golden.json"))
        return (packs, try JSONDecoder().decode(GoldenFile.self, from: data))
    }

    @Test func theCorpusWasBuiltWithTheEmbedderTheAppCarries() throws {
        let (packs, golden) = try load()

        #expect(packs.manifest.embedder.model == golden.embedModel)
        #expect(packs.embedder.descriptor.model == golden.embedModel)
        #expect(packs.embedder.descriptor.dim == packs.manifest.embedder.dim)
    }

    @Test func everyGoldenQueryReproducesItsRecordedHits() async throws {
        let (packs, golden) = try load()
        let retrieval = LocalRetrieval(packs: packs)

        var failures: [String] = []
        for entry in golden.queries {
            for (packName, expected) in entry.packs where !expected.isEmpty {
                guard let scope = Self.scopes[packName] else { continue }

                let result = try await retrieval.retrieve(
                    RetrievalRequest(
                        query: entry.query, corpus: scope, k: golden.k, minScore: 0,
                        semanticFloor: 0))
                let got = result.hits

                let expectedIDs = Set(expected.map(\.nodeID))
                let overlap =
                    Double(Set(got.map(\.nodeId)).intersection(expectedIDs).count)
                    / Double(expectedIDs.count)
                if overlap < golden.tolerance.rankOverlap {
                    failures.append(
                        "[\(packName)] \(entry.query): rank overlap \(String(format: "%.2f", overlap)) "
                            + "< \(golden.tolerance.rankOverlap)")
                }

                // Order, not just membership. The overlap above is a set
                // test, so a result holding the right passages in the wrong
                // sequence passes it — which is exactly how an unconditional
                // sort by cosine survived here. golden.json records the fused
                // order, and RRF's scores are deliberately not monotonic: a
                // literal BM25 match sits above semantic hits with a higher
                // cosine. Comparing only the shared ids keeps this from
                // double-reporting a miss the overlap check already named.
                let shared = got.map(\.nodeId).filter(expectedIDs.contains)
                let sharedSet = Set(shared)
                let referenceOrder = expected.map(\.nodeID).filter(sharedSet.contains)
                let referenceRank = Dictionary(
                    uniqueKeysWithValues: referenceOrder.enumerated().map { ($1, $0) })
                for (position, id) in shared.enumerated() {
                    guard let reference = referenceRank[id] else { continue }
                    let drift = abs(position - reference)
                    if drift > golden.tolerance.maxRankDrift {
                        failures.append(
                            "[\(packName)] \(entry.query): \(id) sits at \(position) "
                                + "but the reference fused it at \(reference) (drift \(drift) "
                                + "> \(golden.tolerance.maxRankDrift))")
                    }
                }

                // Scores are compared only where both sides found the passage;
                // a rank miss is already reported above and would double-count.
                let expectedScores = Dictionary(
                    expected.map { ($0.nodeID, $0.score) }, uniquingKeysWith: { first, _ in first })
                for hit in got {
                    guard let reference = expectedScores[hit.nodeId] else { continue }
                    let delta = abs(hit.score - reference)
                    if delta > golden.tolerance.scoreDelta {
                        failures.append(
                            "[\(packName)] \(entry.query): \(hit.nodeId) scored \(hit.score) "
                                + "vs \(reference) (Δ \(String(format: "%.4f", delta)))")
                    }
                }
            }
        }

        // Report every divergence at once: one failing query is a bug in one
        // place, and all twelve failing is a bug in the tokenizer — telling
        // those apart matters more than failing fast.
        let report = failures.joined(separator: "\n")
        #expect(failures.isEmpty, "\(failures.count) divergence(s):\n\(report)")
    }

    @Test func theLiteralMatchSurvivesTheAllScope() async throws {
        // The regression that shipped: "pillar of salt" fuses the Lot's-wife
        // verse to the top of the books at cosine ~0.59, because BM25 found it
        // where the dense channel could not. Every diary chunk scores ~0.70, so
        // merging the two packs by score dropped the verse clean out of the top
        // ten and the answer said the passages did not mention a pillar of salt
        // -- which was true, and the point. Merging by fused rank keeps it.
        let (packs, _) = try load()
        let retrieval = LocalRetrieval(packs: packs)
        let verse = "the_bible.md:0102"

        for scope in ["gutenberg", "all"] {
            let result = try await retrieval.retrieve(
                RetrievalRequest(query: "pillar of salt", corpus: scope, k: 10, minScore: 0.5))
            let rank = result.hits.firstIndex { $0.nodeId.contains(verse) }
            let found = result.hits.map(\.nodeId).joined(separator: ", ")
            #expect(rank != nil, "[\(scope)] the verse is absent from the top 10: \(found)")
        }
    }

    @Test func aScopedQueryStaysInsideItsGenre() async throws {
        let (packs, _) = try load()
        let retrieval = LocalRetrieval(packs: packs)

        let result = try await retrieval.retrieve(
            RetrievalRequest(query: "pillar of salt", corpus: "sacred-texts", k: 10, minScore: 0))

        #expect(!result.hits.isEmpty)
        #expect(result.hits.allSatisfy { $0.genre == "sacred-texts" })
    }

    @Test func browseWorksFromThePacksAlone() async throws {
        let (packs, _) = try load()
        let browser = LocalBrowser(packs: packs)

        let genres = try await browser.listGenres()
        #expect(!genres.isEmpty)

        let firstGenre = try #require(genres.first)
        let books = try await browser.listBooks(genre: firstGenre.genre)
        #expect(books.count == firstGenre.bookCount)

        let firstBook = try #require(books.first)
        let chapters = try await browser.chapters(genre: firstGenre.genre, book: firstBook.book)
        if let firstChapter = chapters.first {
            let content = try await browser.chapter(
                genre: firstGenre.genre, book: firstBook.book, sectionId: firstChapter.id)
            #expect(!content.text.isEmpty)
        }
    }
}
