// Regenerates src/game/starCatalog.ts from the Yale Bright Star Catalogue
// (5th revised ed., Hoffleit & Warren 1991; CDS catalogue V/50).
//
//   node scripts/build-stars.mjs            fetch from VizieR
//   node scripts/build-stars.mjs bsc.tsv    use a saved copy of the same query
//
// Keeps every star of visual magnitude 6.0 or brighter (the naked-eye sky) and
// writes them as a flat number array, four values per star: right ascension
// and declination in degrees (J2000), visual magnitude, and B-V color index.
import { writeFileSync, readFileSync } from "node:fs";

const QUERY = "https://vizier.cds.unistra.fr/viz-bin/asu-tsv?-source=V/50/catalog"
  + "&-out=HR,RAJ2000,DEJ2000,Vmag,B-V&-out.max=20000&-out.form=|";
const MAG_LIMIT = 6.0;

/** Bright Star numbers of the stars worth naming, for tests and a later "what is that star". */
const NAMED = {
  424: "Polaris", 2491: "Sirius", 2326: "Canopus", 5340: "Arcturus", 7001: "Vega", 1708: "Capella",
  1713: "Rigel", 2943: "Procyon", 2061: "Betelgeuse", 7557: "Altair", 5056: "Spica", 3982: "Regulus",
  8728: "Fomalhaut", 7924: "Deneb", 1457: "Aldebaran", 6134: "Antares", 2990: "Pollux",
};

const arg = process.argv[2];
const text = arg ? readFileSync(arg, "utf8") : await (await fetch(QUERY)).text();

const stars = [];
const named = {};
// Columns are found by name in the header row, so any column order works.
let col = null;
for (const line of text.split("\n")) {
  if (line.startsWith("HR|")) col = Object.fromEntries(line.split("|").map((n, i) => [n.trim(), i]));
  if (line.startsWith("#") || !col || !/^\s*\d+\|/.test(line)) continue;
  const f = line.split("|").map((s) => s.trim());
  const [hr, ra, dec, v, bv] = [f[col.HR], f[col.RAJ2000], f[col.DEJ2000], f[col.Vmag], f[col["B-V"]]];
  const mag = parseFloat(v);
  if (!(mag <= MAG_LIMIT)) continue;
  const [rh, rm, rs] = ra.split(/\s+/).map(Number);
  const sign = dec.startsWith("-") ? -1 : 1;
  const [dd, dm, ds] = dec.replace(/^[+-]/, "").split(/\s+/).map(Number);
  const raDeg = (rh + rm / 60 + rs / 3600) * 15;
  const decDeg = sign * (dd + dm / 60 + ds / 3600);
  // A few stars have no B-V; call them white.
  const color = Number.isFinite(parseFloat(bv)) ? parseFloat(bv) : 0;
  if (NAMED[Number(hr)]) named[NAMED[Number(hr)]] = stars.length / 4;
  stars.push(raDeg.toFixed(3), decDeg.toFixed(3), mag.toFixed(2), color.toFixed(2));
}

const out = `// Generated by scripts/build-stars.mjs from the Yale Bright Star Catalogue, 5th
// revised ed. (Hoffleit & Warren 1991, CDS V/50). Do not edit by hand.

/** Stars of magnitude ${MAG_LIMIT.toFixed(1)} or brighter: ${stars.length / 4}. Four numbers each: RA and Dec in degrees (J2000), V magnitude, B-V. */
export const STAR_DATA: readonly number[] = [
${stars.reduce((rows, s, i) => { if (i % 16 === 0) rows.push([]); rows[rows.length - 1].push(s); return rows; }, []).map((r) => "  " + r.join(",") + ",").join("\n")}
];

/** Index (into STAR_DATA, in stars) of the stars a person would name. */
export const NAMED_STARS: Readonly<Record<string, number>> = ${JSON.stringify(named)};
`;
writeFileSync(new URL("../src/game/starCatalog.ts", import.meta.url), out);
console.log(`${stars.length / 4} stars, ${Object.keys(named).length} named`);
