import type { Book } from "./catalogTypes";

export const BOOKS_PART4: Book[] = [
  {
    slug: "twenty_thousand_leagues_under_the_sea",
    title: "Twenty Thousand Leagues Under the Sea",
    author: "Jules Verne",
    genre: "french-literature",
    genreLabel: "French Literature",
    chunks: 1405,
    excerpt: "Of the echinodermes, remarkable for their coating of spines, asteri, sea-stars, pantacrinæ, comatules, astérophons, echini, holothuri, etc., represented individually a complete collection of this group. A somewhat nervous conchyliologist would certainly have fainted before…",
    tags: ["french-literature"],
  },
  {
    slug: "faust_part_i_goethe",
    title: "Faust Part I (Goethe)",
    author: "Johann Wolfgang von Goethe",
    genre: "german-literature",
    genreLabel: "German Literature",
    chunks: 434,
    excerpt: "Sieh nur, sieh! wie behend sich die Menge Durch die Gärten und Felder zerschlägt, Wie der Fluß, in Breit und Länge So manchen lustigen Nachen bewegt, Und bis zum Sinken überladen Entfernt sich dieser letzte Kahn. Selbst von des Berges fernen Pfaden Blinken uns farbige Kleider…",
    tags: ["german-literature"],
  },
  {
    slug: "faust_der_tragödie_zweiter_teil",
    title: "Faust: Der Tragödie zweiter Teil",
    author: "Johann Wolfgang von Goethe",
    genre: "german-literature",
    genreLabel: "German Literature",
    chunks: 1106,
    excerpt: "Weh! Weh! das brennt! das war ein harter Tritt, + Wie Pferdehuf.",
    tags: ["german-literature"],
  },
  {
    slug: "siddhartha_hesse",
    title: "Siddhartha (Hesse)",
    author: "Hermann Hesse",
    genre: "german-literature",
    genreLabel: "German Literature",
    chunks: 535,
    excerpt: "I wish that you would go it up to its end, oh my friend, that you shall find salvation!” Govinda, not completely understanding it yet, repeated his question in an impatient tone: “Speak up, I beg you, my dear! Tell me, since it could not be any other way, that you also, my…",
    tags: ["german-literature"],
  },
  {
    slug: "the_metamorphosis_kafka",
    title: "The Metamorphosis (Kafka)",
    author: "Franz Kafka",
    genre: "german-literature",
    genreLabel: "German Literature",
    chunks: 290,
    excerpt: "The first few times he tried to climb up on the smooth chest of drawers he just slid down again, but he finally gave himself one last swing and stood there upright; the lower part of his body was in serious pain but he no longer gave any attention to it. Now he let himself…",
    tags: ["german-literature"],
  },
  {
    slug: "the_trial_kafka",
    title: "The Trial (Kafka)",
    author: "Franz Kafka",
    genre: "german-literature",
    genreLabel: "German Literature",
    chunks: 1106,
    excerpt: "\"I have nearly finished what I have to say,\" said K., and as there was no bell available he struck the desk with his fist in a way that startled the judge and his advisor and made them look up from each other. \"None of this concerns me, and I am therefore able to make a calm…",
    tags: ["german-literature"],
  },
  {
    slug: "at_the_mountains_of_madness",
    title: "At the Mountains of Madness",
    author: "H. P. (Howard Phillips) Lovecraft",
    genre: "horror",
    genreLabel: "Horror",
    chunks: 616,
    excerpt: "Wish I had a real laboratory here. Dyer better kick himself for having tried to stop my westward trip. First the world's greatest mountains, and then this. If this last isn't the high spot of the expedition, I don't know what is. We're made scientifically. Congrats, Pabodie,…",
    tags: ["horror"],
  },
  {
    slug: "carmilla",
    title: "Carmilla",
    author: "Joseph Sheridan Le Fanu",
    genre: "horror",
    genreLabel: "Horror",
    chunks: 372,
    excerpt: "You saw how quickly she was gone. I hope I have not done a very foolish thing, in taking charge of the young lady.” For my part, I was delighted. I was longing to see and talk to her; and only waiting till the doctor should give me leave. You, who live in towns, can have no…",
    tags: ["horror"],
  },
  {
    slug: "ghost_stories_of_an_antiquary",
    title: "Ghost Stories of an Antiquary",
    author: "M. R. (Montague Rhodes) James",
    genre: "horror",
    genreLabel: "Horror",
    chunks: 605,
    excerpt: "Those who have taken even the most limited interest in the acquisition of topographical pictures are aware that there is one London dealer whose aid is indispensable to their researches. Mr J. W. Britnell publishes at short intervals very admirable catalogues of a large and…",
    tags: ["horror"],
  },
  {
    slug: "tales_of_terror_and_mystery",
    title: "Tales of Terror and Mystery",
    author: "Arthur Conan Doyle",
    genre: "horror",
    genreLabel: "Horror",
    chunks: 962,
    excerpt: "By Jove, I am chilled to the bone! Come on, Burger, let us warm ourselves by a spurt of hard walking.\" Their footsteps sounded loud and crisp upon the rough stone paving of the disappointing road which is all that is left of the most famous highway of the world. A peasant or…",
    tags: ["horror"],
  },
  {
    slug: "the_call_of_cthulhu",
    title: "The Call of Cthulhu",
    author: "H. P. (Howard Phillips) Lovecraft",
    genre: "horror",
    genreLabel: "Horror",
    chunks: 182,
    excerpt: "On April 2nd at about 3 p. m. every trace of Wilcox's malady suddenly ceased. He sat upright in bed, astonished to find himself at home and completely ignorant of what had happened in dream or reality since the night of March 22nd. Pronounced well by his physician, he…",
    tags: ["horror"],
  },
  {
    slug: "the_case_of_charles_dexter_ward",
    title: "The Case of Charles Dexter Ward",
    author: "H. P. (Howard Phillips) Lovecraft",
    genre: "horror",
    genreLabel: "Horror",
    chunks: 645,
    excerpt: "According to the Smith diary a company of about one hundred men met at ten P.M. on Friday, April twelfth, 1771, in the great room of Thurston's Tavern at the Sign of the Golden Lion on Weybosset Point across the Bridge. Of the guiding group of prominent men in addition to the…",
    tags: ["horror"],
  },
  {
    slug: "the_colour_out_of_space",
    title: "The Colour Out of Space",
    author: "H. P. (Howard Phillips) Lovecraft",
    genre: "horror",
    genreLabel: "Horror",
    chunks: 169,
    excerpt: "The beaker had gone, too, and the wise men talked of the strange stone's affinity for silicon. It had acted quite unbelievably in that well-ordered laboratory; doing nothing at all and showing no occluded gases when heated on charcoal, being wholly negative in the borax bead,…",
    tags: ["horror"],
  },
  {
    slug: "the_dunwich_horror",
    title: "The Dunwich Horror",
    author: "H. P. (Howard Phillips) Lovecraft",
    genre: "horror",
    genreLabel: "Horror",
    chunks: 246,
    excerpt: "This chamber he lined with tall, firm shelving; along which he began gradually to arrange, in apparently careful order, all the rotting ancient books and parts of books which during his own day had been heaped promiscuously in odd corners of the various rooms. \"I made some…",
    tags: ["horror"],
  },
  {
    slug: "the_great_god_pan",
    title: "The Great God Pan",
    author: "Arthur Machen",
    genre: "horror",
    genreLabel: "Horror",
    chunks: 289,
    excerpt: "Thinking, however, that it would be better for the child to have playmates of her own age, he advertised in several local papers for a good home in a comfortable farmhouse for a girl of twelve, and this advertisement was answered by Mr. R., a well-to-do farmer in the…",
    tags: ["horror"],
  },
  {
    slug: "the_house_on_the_borderland",
    title: "The House on the Borderland",
    author: "William Hope Hodgson",
    genre: "horror",
    genreLabel: "Horror",
    chunks: 659,
    excerpt: "We had accomplished perhaps half the distance, when I heard again the sound of falling stones on the other side--the side from which we had just come. One large rock came thundering down through the treetops, struck the opposite bank, and bounded into the river, driving a…",
    tags: ["horror"],
  },
  {
    slug: "the_king_in_yellow",
    title: "The King in Yellow",
    author: "Robert W. (Robert William) Chambers",
    genre: "horror",
    genreLabel: "Horror",
    chunks: 965,
    excerpt: "You know who made you, little humbug!” It was always my rôle to interpret Cupid’s sentiments in these conversations, and when my turn came I responded in such a manner, that Boris seized my arm and dragged me toward the pool, declaring he would duck me.",
    tags: ["horror"],
  },
  {
    slug: "the_monk_a_romance",
    title: "The Monk: A Romance",
    author: "M. G. (Matthew Gregory) Lewis",
    genre: "horror",
    genreLabel: "Horror",
    chunks: 1882,
    excerpt: "This command was issued by the counsels of his Friend, the Duke of Villa Hermosa, a Nobleman for whose abilities and knowledge of the world I have ever entertained the most profound veneration. “Believe me,” said He, “my dear Raymond, you will hereafter feel the benefits of…",
    tags: ["horror"],
  },
  {
    slug: "the_mysteries_of_udolpho",
    title: "The Mysteries of Udolpho",
    author: "Ann Ward Radcliffe",
    genre: "horror",
    genreLabel: "Horror",
    chunks: 4052,
    excerpt: "Had he the presumption to suppose I would marry my niece to a person such as he describes himself!” Emily dried her tears when she heard of the candid confession of Valancourt; and, though the circumstances it discovered were afflicting to her hopes, his artless conduct gave…",
    tags: ["horror"],
  },
  {
    slug: "the_shadow_over_innsmouth",
    title: "The Shadow over Innsmouth",
    author: "H. P. (Howard Phillips) Lovecraft",
    genre: "horror",
    genreLabel: "Horror",
    chunks: 231,
    excerpt: "But as the leaving time obviously approached I conquered my qualms and followed the man aboard, extending him a dollar bill and murmuring the single word \"Innsmouth.\" At length the decrepit vehicle started with a jerk, and rattled noisily past the old brick buildings of State…",
    tags: ["horror"],
  },
  {
    slug: "the_shunned_house",
    title: "The Shunned House",
    author: "H. P. (Howard Phillips) Lovecraft",
    genre: "horror",
    genreLabel: "Horror",
    chunks: 161,
    excerpt: "Rider and Thomas W. Bicknell. He lived with one man-servant in a Georgian homestead with knocker and iron-railed steps, balanced eerily on the steep ascent of North Court Street beside the ancient brick court and colony house where his grandfather--a cousin of that celebrated…",
    tags: ["horror"],
  },
  {
    slug: "the_willows",
    title: "The Willows",
    author: "Algernon Blackwood",
    genre: "horror",
    genreLabel: "Horror",
    chunks: 269,
    excerpt: "We saw its eyes reflecting the sunset, and gleaming an odd yellow as the body turned over. Then it gave a swift, gulping plunge, and dived out of sight in a flash. “An otter, by gad!” we exclaimed in the same breath, laughing. It was an otter, alive, and out on the hunt; yet…",
    tags: ["horror"],
  },
  {
    slug: "letters_of_john_keats_to_his_family_and_friends",
    title: "Letters of John Keats to His Family and Friends",
    author: "John Keats",
    genre: "letters",
    genreLabel: "Letters",
    chunks: 1802,
    excerpt: "Dote upon me, I am a primrose!\" Modern poets differ from the Elizabethans in this: each of the moderns like an Elector of Hanover governs his petty state and knows how many straws are swept daily from the Causeways in all his dominions, and has a continual itching that all…",
    tags: ["letters"],
  },
  {
    slug: "letters_of_pliny_the_younger",
    title: "Letters of Pliny the Younger",
    author: "the Younger Pliny",
    genre: "letters",
    genreLabel: "Letters",
    chunks: 1316,
    excerpt: "He has completed the history which Aufidius Bassus[48] left unfinished, and has added to it thirty books. And lastly he has left thirty-seven books on Natural History, a work of great compass and learning, and as full of variety as nature herself. You will wonder how a man as…",
    tags: ["letters"],
  },
  {
    slug: "letters_on_england",
    title: "Letters on England",
    author: "Voltaire",
    genre: "letters",
    genreLabel: "Letters",
    chunks: 537,
    excerpt: "But these are shameless heretics, who deserve to be blown hence through the flames to old Nick, as Rabelais says, and for this reason I do not trouble myself about them.",
    tags: ["letters"],
  },
  {
    slug: "letters_to_his_son_lord_chesterfield",
    title: "Letters to His Son — Lord Chesterfield",
    author: "Philip Dormer Stanhope, Earl of Chesterfield",
    genre: "letters",
    genreLabel: "Letters",
    chunks: 612,
    excerpt: "LONDON, April 1, O. S. 1748. DEAR BOY: I have not received any letter, either from you or from Mr. Harte, these three posts, which I impute wholly to accidents between this place and Leipsig; and they are distant enough to admit of many.",
    tags: ["letters"],
  },
  {
    slug: "the_works_of_lord_byron_letters_and_journals_vol_1",
    title: "The Works of Lord Byron: Letters and Journals. Vol. 1",
    author: "George Gordon Byron, Baron Byron",
    genre: "letters",
    genreLabel: "Letters",
    chunks: 1787,
    excerpt: "I saw them walk to St. George's Chapel, which was the best part, as it did not last long ... Their dresses were very magnificent. The Knights, before they were installed, were in white and silver, like the old pictures of Henry VIII., and afterwards they had a purple mantle…",
    tags: ["letters"],
  },
  {
    slug: "the_works_of_lord_byron_letters_and_journals_vol_2",
    title: "The Works of Lord Byron: Letters and Journals. Vol. 2",
    author: "George Gordon Byron, Baron Byron",
    genre: "letters",
    genreLabel: "Letters",
    chunks: 2397,
    excerpt: "You censure _my_ life, Harness,--when I compare myself with these men, my elders and my betters, I really begin to conceive myself a monument of prudence--a walking statue--without feeling or failing; and yet the world in general hath given me a proud pre-eminence over them…",
    tags: ["letters"],
  },
  {
    slug: "autobiography_of_charles_darwin",
    title: "Autobiography of Charles Darwin",
    author: "Charles Darwin",
    genre: "natural-history",
    genreLabel: "Natural History",
    chunks: 320,
    excerpt: "So that I felt the keenest delight when I first read of the action of icebergs in transporting boulders, and I gloried in the progress of Geology.",
    tags: ["natural-history"],
  },
  {
    slug: "mans_place_in_nature_thomas_h_huxley",
    title: "Man's Place in Nature — Thomas H. Huxley",
    author: "Thomas Henry Huxley",
    genre: "natural-history",
    genreLabel: "Natural History",
    chunks: 247,
    excerpt: "The Abbe Prevost and Buffon between them, however, did a good deal more disfigurement to Battell's sober account than 'cutting off an article.' Thus Battell's statement that the Pongos \"cannot speake, and have no understanding more than a beast,\" is rendered by Buffon \"qu'il…",
    tags: ["natural-history"],
  },
  {
    slug: "on_the_origin_of_species_charles_darwin",
    title: "On the Origin of Species — Charles Darwin",
    author: "Charles Darwin",
    genre: "natural-history",
    genreLabel: "Natural History",
    chunks: 2329,
    excerpt: "In many other cases, far from there being any aids for self-fertilisation, there are special contrivances, as I could show from the writings of C. C.",
    tags: ["natural-history"],
  },
  {
    slug: "the_chemical_history_of_a_candle_michael_faraday",
    title: "The Chemical History of a Candle — Michael Faraday",
    author: "Michael Faraday",
    genre: "natural-history",
    genreLabel: "Natural History",
    chunks: 547,
    excerpt: "These things may all be very properly used if you take care; but without that, much mischief will be done.) Well, then, here is a little gunpowder, which I put at the bottom of that little wooden vessel, and mix the iron filings up with it, my object being to make the…",
    tags: ["natural-history"],
  },
  {
    slug: "the_descent_of_man_charles_darwin",
    title: "The Descent of Man — Charles Darwin",
    author: "Charles Darwin",
    genre: "natural-history",
    genreLabel: "Natural History",
    chunks: 4564,
    excerpt: "Mr. Wallace gives cases in his ‘Contributions to the Theory of Natural Selection,’ 1870, p. 354.), would not feel remorse in his inmost soul, if he had failed in a duty, which he held sacred. We may therefore conclude that primeval man, at a very remote period, was influenced…",
    tags: ["natural-history"],
  },
  {
    slug: "the_malay_archipelago_alfred_russel_wallace",
    title: "The Malay Archipelago — Alfred Russel Wallace",
    author: "Alfred Russel Wallace",
    genre: "natural-history",
    genreLabel: "Natural History",
    chunks: 1593,
    excerpt: "In preparing the skins and skeletons of these animals, I was much troubled by the Dyak dogs, which, being always kept in a state of semi-starvation, are ravenous for animal food. I had a great iron pan, in which I boiled the bones to make skeletons, and at night I covered…",
    tags: ["natural-history"],
  },
  {
    slug: "the_voyage_of_the_beagle_charles_darwin",
    title: "The Voyage of the Beagle — Charles Darwin",
    author: "Charles Darwin",
    genre: "natural-history",
    genreLabel: "Natural History",
    chunks: 2846,
    excerpt: "They turned out to be messengers or ambassadors from a large body of Indians, united in the common cause of defence, near the Cordillera. The tribe to which they had been sent was on the point of holding a grand council, the feast of mare's flesh was ready, and the dance…",
    tags: ["natural-history"],
  },
  {
    slug: "a_pickle_for_the_knowing_ones",
    title: "A Pickle for the Knowing Ones",
    author: "Timothy Dexter",
    genre: "philosophy",
    genreLabel: "Philosophy",
    chunks: 103,
    excerpt: "She thought him an honest man, and not so deficient in intellect as many people supposed, and attributed his eccentricities to an excess of animal spirits.--This was probably to some extent true, though it is certain that other spirits contributed in no small degree to the…",
    tags: ["philosophy"],
  },
  {
    slug: "a_vindication_of_the_rights_of_woman_wollstonecraft",
    title: "A Vindication of the Rights of Woman (Wollstonecraft)",
    author: "Mary Wollstonecraft",
    genre: "philosophy",
    genreLabel: "Philosophy",
    chunks: 1281,
    excerpt: "Women, as well as despots, have now, perhaps, more power than they would have, if the world, divided and subdivided into kingdoms and families, was governed by laws deduced from the exercise of reason; but in obtaining it, to carry on the comparison, their character is…",
    tags: ["philosophy"],
  },
  {
    slug: "apology_plato",
    title: "Apology (Plato)",
    author: "Plato",
    genre: "philosophy",
    genreLabel: "Philosophy",
    chunks: 213,
    excerpt: "Or are these sophistries to be regarded as belonging to the age in which he lived and to his personal character, and this apparent haughtiness as flowing from the natural elevation of his position?",
    tags: ["philosophy"],
  },
  {
    slug: "beyond_good_and_evil",
    title: "Beyond Good and Evil",
    author: "Friedrich Wilhelm Nietzsche",
    genre: "philosophy",
    genreLabel: "Philosophy",
    chunks: 861,
    excerpt: "There is far too much witchery and sugar in the sentiments \"for others\" and \"NOT for myself,\" for one not needing to be doubly distrustful here, and for one asking promptly: \"Are they not perhaps--DECEPTIONS?\"--That they PLEASE--him who has them, and him who enjoys their…",
    tags: ["philosophy"],
  },
  {
    slug: "common_sense",
    title: "Common Sense",
    author: "Thomas Paine",
    genre: "philosophy",
    genreLabel: "Philosophy",
    chunks: 302,
    excerpt: "And a man hath good reason to believe that there is as much of king-craft, as priest-craft, in withholding the scripture from the public in Popish countries. For monarchy in every instance is the Popery of government. To the evil of monarchy we have added that of hereditary…",
    tags: ["philosophy"],
  },
  {
    slug: "critique_of_pure_reason_kant",
    title: "Critique of Pure Reason (Kant)",
    author: "Immanuel Kant",
    genre: "philosophy",
    genreLabel: "Philosophy",
    chunks: 3205,
    excerpt: "But if I investigate more closely the relation of given cognitions in every judgement, and distinguish it, as belonging to the understanding, from the relation which is produced according to laws of the reproductive imagination (which has only subjective validity), I find…",
    tags: ["philosophy"],
  },
  {
    slug: "discourse_on_the_method_of_rightly_conducting_ones_reason_an",
    title: "Discourse on the Method of Rightly Conducting One's Reason and of Seeking Truth in the Sciences",
    author: "René Descartes",
    genre: "philosophy",
    genreLabel: "Philosophy",
    chunks: 257,
    excerpt: "For my own part, I should doubtless have belonged to the latter class, had I received instruction from but one master, or had I never known the diversities of opinion that from time immemorial have prevailed among men of the greatest learning.",
    tags: ["philosophy"],
  },
  {
    slug: "ecce_homo",
    title: "Ecce Homo",
    author: "Friedrich Wilhelm Nietzsche",
    genre: "philosophy",
    genreLabel: "Philosophy",
    chunks: 675,
    excerpt: "The best cooking is that of Piedmont. Alcoholic drinks do not agree with me; a single glass of wine or beer a day is amply sufficient to turn life into a valley of tears for me;--in Munich live my antipodes. Although I admit that this knowledge came to me somewhat late, it…",
    tags: ["philosophy"],
  },
];
