import type { Book } from "./catalogTypes";

export const BOOKS_PART5: Book[] = [
  {
    slug: "essays_first_and_second_series_emerson",
    title: "Essays — First and Second Series (Emerson)",
    author: "Ralph Waldo Emerson",
    genre: "philosophy",
    genreLabel: "Philosophy",
    chunks: 986,
    excerpt: "Check this lying hospitality and lying affection. Live no longer to the expectation of these deceived and deceiving people with whom we converse. Say to them, ‘O father, O mother, O wife, O brother, O friend, I have lived with you after appearances hitherto. Henceforward I am…",
    tags: ["philosophy"],
  },
  {
    slug: "groundwork_of_the_metaphysics_of_morals_kant",
    title: "Groundwork of the Metaphysics of Morals (Kant)",
    author: "Immanuel Kant",
    genre: "philosophy",
    genreLabel: "Philosophy",
    chunks: 430,
    excerpt: "But what sort of law can that be, the conception of which must determine the will, even without paying any regard to the effect expected from it, in order that this will may be called good absolutely and without qualification?",
    tags: ["philosophy"],
  },
  {
    slug: "hegels_lectures_on_the_history_of_philosophy_volume_3_of_3",
    title: "Hegel's Lectures on the History of Philosophy: Volume 3 (of 3)",
    author: "Georg Wilhelm Friedrich Hegel",
    genre: "philosophy",
    genreLabel: "Philosophy",
    chunks: 2802,
    excerpt: "Their fate, their lives, their writings—which often fill many volumes—manifest only this restlessness of their being, this tearing asunder, the revolt of their inner being against present existence and the longing to get out of it and reach certainty. These remarkable…",
    tags: ["philosophy"],
  },
  {
    slug: "leviathan",
    title: "Leviathan",
    author: "Thomas Hobbes",
    genre: "philosophy",
    genreLabel: "Philosophy",
    chunks: 2921,
    excerpt: "Therefore a Righteous man, does not lose that Title, by one, or a few unjust Actions, that proceed from sudden Passion, or mistake of Things, or Persons: nor does an Unrighteous man, lose his character, for such Actions, as he does, of forbeares to do, for feare: because his…",
    tags: ["philosophy"],
  },
  {
    slug: "meditations",
    title: "Meditations",
    author: "Emperor of Rome Marcus Aurelius",
    genre: "philosophy",
    genreLabel: "Philosophy",
    chunks: 967,
    excerpt: "To follow reason for ordinary duties and actions is common to them also, who believe not that there be any gods, and for their advantage would make no conscience to betray their own country; and who when once the doors be shut upon them, dare do anything.",
    tags: ["philosophy"],
  },
  {
    slug: "nicomachean_ethics_aristotle",
    title: "Nicomachean Ethics (Aristotle)",
    author: "Aristotle",
    genre: "philosophy",
    genreLabel: "Philosophy",
    chunks: 1521,
    excerpt: "These things then to which the bias is, we call more contrary, and so total want of self-control (the excess) is more contrary than the defect is to perfected self-mastery.",
    tags: ["philosophy"],
  },
  {
    slug: "on_liberty_mill",
    title: "On Liberty (Mill)",
    author: "John Stuart Mill",
    genre: "philosophy",
    genreLabel: "Philosophy",
    chunks: 776,
    excerpt: "It is necessary to consider separately these two hypotheses, each of which has a distinct branch of the argument corresponding to it. We can never be sure that the opinion we are endeavouring to stifle is a false opinion; and if we were sure, stifling it would be an evil…",
    tags: ["philosophy"],
  },
  {
    slug: "on_the_duty_of_civil_disobedience_thoreau",
    title: "On the Duty of Civil Disobedience (Thoreau)",
    author: "Henry David Thoreau",
    genre: "philosophy",
    genreLabel: "Philosophy",
    chunks: 133,
    excerpt: "In their practice, nations agree with Paley; but does anyone think that Massachusetts does exactly what is right at the present crisis? “A drab of state, a cloth-o’-silver slut, To have her train borne up, and her soul trail in the dirt.” Practically speaking, the opponents…",
    tags: ["philosophy"],
  },
  {
    slug: "phaedo_plato",
    title: "Phaedo (Plato)",
    author: "Plato",
    genre: "philosophy",
    genreLabel: "Philosophy",
    chunks: 567,
    excerpt: "The last ground of our belief in immortality, and the strongest, is the perfection of the divine nature. The mere fact of the existence of God does not tend to show the continued existence of man. An evil God or an indifferent God might have had the power, but not the will,…",
    tags: ["philosophy"],
  },
  {
    slug: "plutarchs_morals",
    title: "Plutarch's Morals",
    author: "Plutarch",
    genre: "philosophy",
    genreLabel: "Philosophy",
    chunks: 2139,
    excerpt: "But if a wife be by nature austere and apathetic, and no lover of pleasure, the husband must make the best of it, for, as Phocion said, when Antipater enjoined on him an action neither honourable nor becoming, \"You cannot have me as a friend and flatterer both,\" so he must…",
    tags: ["philosophy"],
  },
  {
    slug: "poetics_aristotle",
    title: "Poetics (Aristotle)",
    author: "Aristotle",
    genre: "philosophy",
    genreLabel: "Philosophy",
    chunks: 214,
    excerpt: "Again, if you string together a set of speeches expressive of character, and well finished in point of diction and thought, you will not produce the essential tragic effect nearly so well as with a play which, however deficient in these respects, yet has a plot and…",
    tags: ["philosophy"],
  },
  {
    slug: "politics_aristotle",
    title: "Politics (Aristotle)",
    author: "Aristotle",
    genre: "philosophy",
    genreLabel: "Philosophy",
    chunks: 1193,
    excerpt: "By this means he says he shall necessarily have an equal number of each rank, but he is mistaken--for the majority will always consist of those of the first rank, and the most considerable people; and for this reason, that many of the commonalty not being obliged to it, will…",
    tags: ["philosophy"],
  },
  {
    slug: "second_treatise_of_government",
    title: "Second Treatise of Government",
    author: "John Locke",
    genre: "philosophy",
    genreLabel: "Philosophy",
    chunks: 669,
    excerpt: "And if he also bartered away plums, that would have rotted in a week, for nuts that would last good for his eating a whole year, he did no injury; he wasted not the common stock; destroyed no part of the portion of goods that belonged to others, so long as nothing perished…",
    tags: ["philosophy"],
  },
  {
    slug: "the_art_of_war_sun_tzu",
    title: "The Art of War (Sun Tzu)",
    author: "active 6th century B.C. Sunzi",
    genre: "philosophy",
    genreLabel: "Philosophy",
    chunks: 763,
    excerpt: "In spite of all this, the great body of Chinese sentiment, from Lao Tzŭ downwards, and especially as reflected in the standard literature of Confucianism, has been consistently pacific and intensely opposed to militarism in any form. It is such an uncommon thing to find any…",
    tags: ["philosophy"],
  },
  {
    slug: "the_birth_of_tragedy_or_hellenism_and_pessimism",
    title: "The Birth of Tragedy; or, Hellenism and Pessimism",
    author: "Friedrich Wilhelm Nietzsche",
    genre: "philosophy",
    genreLabel: "Philosophy",
    chunks: 784,
    excerpt: "But also that delicate line, which the dream-picture must not overstep--lest it act pathologically (in which case appearance, being reality pure and simple, would impose upon us)--must not be wanting in the picture of Apollo: that measured limitation, that freedom from the…",
    tags: ["philosophy"],
  },
  {
    slug: "the_city_of_god_volume_i",
    title: "The City of God, Volume I",
    author: "of Hippo, Saint Augustine",
    genre: "philosophy",
    genreLabel: "Philosophy",
    chunks: 2899,
    excerpt: "But, in Numa's reign, I would know whether the long peace was maintained in spite of the incursions of wicked neighbours, or if these incursions were discontinued that the peace might be maintained? For if even then Rome was harassed by wars, and yet did not meet force with…",
    tags: ["philosophy"],
  },
  {
    slug: "the_crown_of_wild_olive",
    title: "The Crown of Wild Olive",
    author: "John Ruskin",
    genre: "philosophy",
    genreLabel: "Philosophy",
    chunks: 4221,
    excerpt: "It is no otherwise withdrawn if I bury it, nor even if I choose to make it, and others, into a golden cup, and drink out of them; since a rise in the price of the wine, or of other things, may at any time cause me to melt the cup and throw it back into currency; and the…",
    tags: ["philosophy"],
  },
  {
    slug: "the_enchiridion",
    title: "The Enchiridion",
    author: "Epictetus",
    genre: "philosophy",
    genreLabel: "Philosophy",
    chunks: 174,
    excerpt: "Epictetus had taught him that philosophical reason could make him free and that he was capable of redeeming himself by sound reasoning. In the Stoic distinctions of personality and world, of I and mine, of subjective consciousness and the world of objects, of freedom and…",
    tags: ["philosophy"],
  },
  {
    slug: "the_federalist_papers",
    title: "The Federalist Papers",
    author: "James Madison",
    genre: "philosophy",
    genreLabel: "Philosophy",
    chunks: 2904,
    excerpt: "Controversies and wars among the members themselves have been so common, that the German annals are crowded with the bloody pages which describe them. Previous to the peace of Westphalia, Germany was desolated by a war of thirty years, in which the emperor, with one half of…",
    tags: ["philosophy"],
  },
  {
    slug: "the_kama_sutra_of_vatsyayana",
    title: "The Kama Sutra of Vatsyayana",
    author: "Vatsyayana",
    genre: "philosophy",
    genreLabel: "Philosophy",
    chunks: 795,
    excerpt: "On the other hand when the female exceeds the male in point of size, her union with a man immediately next to her in size is called low union, and is of two kinds; while her union with a man most remote from her in size is called the lowest union, and is of one kind only. In…",
    tags: ["philosophy"],
  },
  {
    slug: "the_lives_and_opinions_of_eminent_philosophers",
    title: "The Lives and Opinions of Eminent Philosophers",
    author: "Diogenes Laertius",
    genre: "philosophy",
    genreLabel: "Philosophy",
    chunks: 2408,
    excerpt: "III. He is, as some people say, the first writer who reduced the conversations of Socrates into the form of dialogues. And when Pericles offered to provide for him, and invited him to come to him, he said that he would not sell his freedom of speech. IV. There was also…",
    tags: ["philosophy"],
  },
  {
    slug: "the_prince",
    title: "The Prince",
    author: "Niccolò Machiavelli",
    genre: "philosophy",
    genreLabel: "Philosophy",
    chunks: 704,
    excerpt: "Further, it facilitates matters when the prince, having no other state, is compelled to reside there in person. But to come to those who, by their own ability and not through fortune, have risen to be princes, I say that Moses, Cyrus, Romulus, Theseus, and such like are the…",
    tags: ["philosophy"],
  },
  {
    slug: "the_problems_of_philosophy_russell",
    title: "The Problems of Philosophy (Russell)",
    author: "Bertrand Russell",
    genre: "philosophy",
    genreLabel: "Philosophy",
    chunks: 605,
    excerpt: "Thus the colour we see is a result of the ray as it reaches the eye, and not simply a property of the object from which the ray comes. Hence, also, provided certain waves reach the eye, we shall see a certain colour, whether the object from which the waves start has any…",
    tags: ["philosophy"],
  },
  {
    slug: "the_republic",
    title: "The Republic",
    author: "Plato",
    genre: "philosophy",
    genreLabel: "Philosophy",
    chunks: 2900,
    excerpt: "But now imagine further, that they descend into their old habitations;—in that underground dwelling they will not see as well as their fellows, and will not be able to compete with them in the measurement of the shadows on the wall; there will be many jokes about the man who…",
    tags: ["philosophy"],
  },
  {
    slug: "the_social_contract_rousseau",
    title: "The Social Contract (Rousseau)",
    author: "Jean-Jacques Rousseau",
    genre: "philosophy",
    genreLabel: "Philosophy",
    chunks: 1748,
    excerpt: "Sometimes they confuse all these sections, and sometimes they distinguish them; they turn the Sovereign into a fantastic being composed of several connected pieces: it is as if they were making man of several bodies, one with eyes, one with arms, another with feet, and each…",
    tags: ["philosophy"],
  },
  {
    slug: "the_symposium_plato",
    title: "The Symposium (Plato)",
    author: "Plato",
    genre: "philosophy",
    genreLabel: "Philosophy",
    chunks: 435,
    excerpt: "Like the sophists and like Plato himself, though in a different sense, he begins his discussion by an appeal to mythology, and distinguishes between the elder and younger love. The value which he attributes to such loves as motives to virtue and philosophy is at variance with…",
    tags: ["philosophy"],
  },
  {
    slug: "the_twilight_of_the_idols_or_how_to_philosophize_with_the_ha",
    title: "The Twilight of the Idols; or, How to Philosophize with the Hammer. The Antichrist",
    author: "Friedrich Wilhelm Nietzsche",
    genre: "philosophy",
    genreLabel: "Philosophy",
    chunks: 995,
    excerpt: "Christianity as sprung from Jewish roots and comprehensible only as grown upon this soil, represents the counter-movement against that morality of breeding, of race and of privilege:—it is essentially an anti-Aryan religion: Christianity is the transvaluation of all Aryan…",
    tags: ["philosophy"],
  },
  {
    slug: "the_wealth_of_nations",
    title: "The Wealth of Nations",
    author: "Adam Smith",
    genre: "philosophy",
    genreLabel: "Philosophy",
    chunks: 5469,
    excerpt: "These, however, though the highest, are by no means the only high prices which seem to have been occasioned by the civil wars. The second event was the bounty upon the exportation of corn, granted in 1688. The bounty, it has been thought by many people, by encouraging…",
    tags: ["philosophy"],
  },
  {
    slug: "the_origin_and_development_of_the_moral_ideas",
    title: "The origin and development of the moral ideas",
    author: "Edward Westermarck",
    genre: "philosophy",
    genreLabel: "Philosophy",
    chunks: 7652,
    excerpt: "Even a dog which, in playing with another dog, hurts itself, for instance, by running into a tree, changes its angry attitude immediately it notices the real nature of that which caused it pain.[1] [Footnote 1: Hiram Stanley, _Studies in the Evolutionary Psychology of…",
    tags: ["philosophy"],
  },
  {
    slug: "thus_spake_zarathustra",
    title: "Thus Spake Zarathustra",
    author: "Friedrich Wilhelm Nietzsche",
    genre: "philosophy",
    genreLabel: "Philosophy",
    chunks: 1487,
    excerpt: "Every one regardeth dying as a great matter: but as yet death is not a festival. Not yet have people learned to inaugurate the finest festivals. The consummating death I show unto you, which becometh a stimulus and promise to the living. His death, dieth the consummating one…",
    tags: ["philosophy"],
  },
  {
    slug: "utilitarianism_mill",
    title: "Utilitarianism (Mill)",
    author: "John Stuart Mill",
    genre: "philosophy",
    genreLabel: "Philosophy",
    chunks: 399,
    excerpt: "The objectors perhaps may doubt whether human beings, if taught to consider happiness as the end of life, would be satisfied with such a moderate share of it. But great numbers of mankind have been satisfied with much less. The main constituents of a satisfied life appear to…",
    tags: ["philosophy"],
  },
  {
    slug: "anna_karenina",
    title: "Anna Karenina",
    author: "Leo, graf Tolstoy",
    genre: "russian-literature",
    genreLabel: "Russian Literature",
    chunks: 4837,
    excerpt: "He stood, listened, and gazed sometimes down at the wet mossy ground, sometimes at Laska listening all alert, sometimes at the sea of bare tree tops that stretched on the slope below him, sometimes at the darkening sky, covered with white streaks of cloud. A hawk flew high…",
    tags: ["russian-literature"],
  },
  {
    slug: "childhood_boyhood_youth_tolstoy",
    title: "Childhood, Boyhood, Youth (Tolstoy)",
    author: "Leo, graf Tolstoy",
    genre: "russian-literature",
    genreLabel: "Russian Literature",
    chunks: 397,
    excerpt: "When for the first time Woloda wore Dutch pleated shirts, I at once said that I was greatly put out at not being given similar ones, and each time that he arranged his collar, I felt that he was doing so on purpose to offend me. But, what tormented me most of all was the idea…",
    tags: ["russian-literature"],
  },
  {
    slug: "crime_and_punishment",
    title: "Crime and Punishment",
    author: "Fyodor Dostoyevsky",
    genre: "russian-literature",
    genreLabel: "Russian Literature",
    chunks: 2728,
    excerpt: "But a year ago, the girl died of typhus. I remained lodging there as before, and when my landlady moved into her present quarters, she said to me... and in a friendly way... that she had complete trust in me, but still, would I not give her an I O U for one hundred and…",
    tags: ["russian-literature"],
  },
  {
    slug: "dead_souls",
    title: "Dead Souls",
    author: "Nikolai Vasilevich Gogol",
    genre: "russian-literature",
    genreLabel: "Russian Literature",
    chunks: 1946,
    excerpt: "Indeed, the pair would have entered into conversation, and have made one another’s acquaintance (since a beginning was made with their simultaneously expressing satisfaction at the circumstance that the previous night’s rain had laid the dust on the roads, and thereby made…",
    tags: ["russian-literature"],
  },
  {
    slug: "fathers_and_sons_turgenev",
    title: "Fathers and Sons (Turgenev)",
    author: "Ivan Sergeevich Turgenev",
    genre: "russian-literature",
    genreLabel: "Russian Literature",
    chunks: 1040,
    excerpt: "'Oh, yes, the curtains; Nikolai Petrovitch was so good as to make me a present of them; but they have been put up a long while now.' 'Yes, and it's a long while since I have been to see you. Now it is very nice here.' 'Thanks to Nikolai Petrovitch's kindness,' murmured…",
    tags: ["russian-literature"],
  },
  {
    slug: "notes_from_underground_dostoevsky",
    title: "Notes from Underground (Dostoevsky)",
    author: "Fyodor Dostoyevsky",
    genre: "russian-literature",
    genreLabel: "Russian Literature",
    chunks: 579,
    excerpt: "And as all choice and reasoning can be really calculated—because there will some day be discovered the laws of our so-called free will—so, joking apart, there may one day be something like a table constructed of them, so that we really shall choose in accordance with it.",
    tags: ["russian-literature"],
  },
  {
    slug: "oblomov",
    title: "Oblomov",
    author: "Ivan Aleksandrovich Goncharov",
    genre: "russian-literature",
    genreLabel: "Russian Literature",
    chunks: 819,
    excerpt: "The doctor reflected a moment. “Yes; also get the benefit of sea air,” he said. “Cross over to England, or else go for a voyage to America.” With chat he rose to take his leave. “Should you carry out these instructions to the letter----” he began. “Yes, yes. Of _course_ I…",
    tags: ["russian-literature"],
  },
  {
    slug: "on_the_eve_a_novel",
    title: "On the eve: A novel",
    author: "Ivan Sergeevich Turgenev",
    genre: "russian-literature",
    genreLabel: "Russian Literature",
    chunks: 803,
    excerpt: "Of late years she had behaved to her mother as to a sick grandmother; while her father, who had been proud of her while she had been regarded as an exceptional child, had come to be afraid of her when she was grown up, and said of her that she was a sort of enthusiastic…",
    tags: ["russian-literature"],
  },
  {
    slug: "the_brothers_karamazov",
    title: "The Brothers Karamazov",
    author: "Fyodor Dostoyevsky",
    genre: "russian-literature",
    genreLabel: "Russian Literature",
    chunks: 4690,
    excerpt: "But a minute later he laughed again just as softly and happily. He slowly replaced the note in the envelope, crossed himself and lay down. The agitation in his heart passed at once. “God, have mercy upon all of them, have all these unhappy and turbulent souls in Thy keeping,…",
    tags: ["russian-literature"],
  },
  {
    slug: "the_idiot",
    title: "The Idiot",
    author: "Fyodor Dostoyevsky",
    genre: "russian-literature",
    genreLabel: "Russian Literature",
    chunks: 3255,
    excerpt: "The prince was in despair. He felt that though he had but applied to this miserable old drunkard because he saw no other way of getting to Nastasia Philipovna’s, yet he had been very wrong to put the slightest confidence in such a man. At last he rose and declared that he…",
    tags: ["russian-literature"],
  },
  {
    slug: "the_possessed_or_the_devils",
    title: "The possessed :  or, The devils",
    author: "Fyodor Dostoyevsky",
    genre: "russian-literature",
    genreLabel: "Russian Literature",
    chunks: 3425,
    excerpt: "\"If it's not arranged by to-morrow, though, I shall go myself whatever happens, and even if every one were to know.\" \"I can't be with you before three o'clock to-morrow,\" I observed, after a moment's deliberation. \"At three o'clock then. Then it was true what I imagined…",
    tags: ["russian-literature"],
  },
  {
    slug: "war_and_peace",
    title: "War and Peace",
    author: "Leo, graf Tolstoy",
    genre: "russian-literature",
    genreLabel: "Russian Literature",
    chunks: 7846,
    excerpt: "He said he would not have been taken, it was not his fault but the corporal’s who had sent him to seize some horsecloths, though he had told him the Russians were there. And at every word he added: “But don’t hurt my little horse!” and stroked the animal. It was plain that he…",
    tags: ["russian-literature"],
  },
];
