import type { Book } from "./catalogTypes";

export const BOOKS_PART3: Book[] = [
  {
    slug: "cranford_gaskell",
    title: "Cranford (Gaskell)",
    author: "Elizabeth Cleghorn Gaskell",
    genre: "english-literature",
    genreLabel: "English Literature",
    chunks: 942,
    excerpt: "Then we had suet puddings, boiled in the broth with the beef: and then the meat itself. If we did not sup our broth, we had no ball, which we liked a deal better; and the beef came last of all, and only those had it who had done justice to the broth and the ball. Now folks…",
    tags: ["english-literature"],
  },
  {
    slug: "david_copperfield_dickens",
    title: "David Copperfield (Dickens)",
    author: "Charles Dickens",
    genre: "english-literature",
    genreLabel: "English Literature",
    chunks: 4717,
    excerpt: "I had barely time to get down again before the coach started, and I could hardly see the family for the handkerchiefs they waved. It was gone in a minute. The Orfling and I stood looking vacantly at each other in the middle of the road, and then shook hands and said good-bye;…",
    tags: ["english-literature"],
  },
  {
    slug: "dracula",
    title: "Dracula",
    author: "Bram Stoker",
    genre: "english-literature",
    genreLabel: "English Literature",
    chunks: 2016,
    excerpt: "His mouth moved as though he were praying. After a few minutes’ silence, he got up, shook hands with me, and blessed me, and said good-bye, and hobbled off. It all touched me, and upset me very much. I was glad when the coastguard came along, with his spy-glass under his arm.…",
    tags: ["english-literature"],
  },
  {
    slug: "emma",
    title: "Emma",
    author: "Jane Austen",
    genre: "english-literature",
    genreLabel: "English Literature",
    chunks: 2144,
    excerpt: "Come, my dear Emma, let us be friends, and say no more about it. Tell your aunt, little Emma, that she ought to set you a better example than to be renewing old grievances, and that if she were not wrong before, she is now.” “That’s true,” she cried—“very true. Little Emma,…",
    tags: ["english-literature"],
  },
  {
    slug: "far_from_the_madding_crowd_hardy",
    title: "Far from the Madding Crowd (Hardy)",
    author: "Thomas Hardy",
    genre: "english-literature",
    genreLabel: "English Literature",
    chunks: 1860,
    excerpt: "Every looker-on’s inside shook with the blows of the great drum to his deepest vitals, and there was not a dry eye throughout the town among the public-house people and the nameless women!” “But they’re not gone to any war?” “No, ma’am; but they be gone to take the places of…",
    tags: ["english-literature"],
  },
  {
    slug: "great_expectations",
    title: "Great Expectations",
    author: "Charles Dickens",
    genre: "english-literature",
    genreLabel: "English Literature",
    chunks: 2432,
    excerpt: "She was seated at her dressing-table, and looked round at us immediately. “Oh!” said she to Joe. “You are the husband of the sister of this boy?” I could hardly have imagined dear old Joe looking so unlike himself or so like some extraordinary bird; standing as he did…",
    tags: ["english-literature"],
  },
  {
    slug: "grimms_fairy_tales",
    title: "Grimms Fairy Tales",
    author: "Wilhelm Grimm",
    genre: "english-literature",
    genreLabel: "English Literature",
    chunks: 1218,
    excerpt: "All this the old king saw: so he went home without being seen; and when the little goose-girl came back in the evening he called her aside, and asked her why she did so: but she burst into tears, and said, ‘That I must not tell you or any man, or I shall lose my life.’ But…",
    tags: ["english-literature"],
  },
  {
    slug: "gullivers_travels",
    title: "Gullivers Travels",
    author: "Jonathan Swift",
    genre: "english-literature",
    genreLabel: "English Literature",
    chunks: 1328,
    excerpt: "He represented to the emperor “the low condition of his treasury; that he was forced to take up money at a great discount; that exchequer bills would not circulate under nine per cent. below par; that I had cost his majesty above a million and a half of _sprugs_” (their…",
    tags: ["english-literature"],
  },
  {
    slug: "heart_of_darkness",
    title: "Heart of Darkness",
    author: "Joseph Conrad",
    genre: "english-literature",
    genreLabel: "English Literature",
    chunks: 510,
    excerpt: "Strings of dusty niggers with splay feet arrived and departed; a stream of manufactured goods, rubbishy cottons, beads, and brass-wire sent into the depths of darkness, and in return came a precious trickle of ivory. “I had to wait in the station for ten days—an eternity. I…",
    tags: ["english-literature"],
  },
  {
    slug: "howards_end",
    title: "Howards End",
    author: "E. M. (Edward Morgan) Forster",
    genre: "english-literature",
    genreLabel: "English Literature",
    chunks: 1475,
    excerpt: "Now and then I do.” “I thought of you as one of the early risers.” “At Howards End—yes; there is nothing to get up for in London.” “Nothing to get up for?” cried the scandalized Margaret. “When there are all the autumn exhibitions, and Ysaye playing in the afternoon! Not to…",
    tags: ["english-literature"],
  },
  {
    slug: "jane_eyre",
    title: "Jane Eyre",
    author: "Charlotte Brontë",
    genre: "english-literature",
    genreLabel: "English Literature",
    chunks: 2478,
    excerpt: "It is a very strange sensation to inexperienced youth to feel itself quite alone in the world, cut adrift from every connection, uncertain whether the port to which it is bound can be reached, and prevented by many impediments from returning to that it has quitted. The charm…",
    tags: ["english-literature"],
  },
  {
    slug: "kim_kipling",
    title: "Kim (Kipling)",
    author: "Rudyard Kipling",
    genre: "english-literature",
    genreLabel: "English Literature",
    chunks: 1410,
    excerpt: "The old man’s face lit with pride. “My child!” said he briefly, and strove to rein the pony’s neck to a fitting arch. “Am I to be beaten before the police?” cried the carter. “Justice! I will have Justice—” “Am I to be blocked by a shouting ape who upsets ten thousand sacks…",
    tags: ["english-literature"],
  },
  {
    slug: "middlemarch",
    title: "Middlemarch",
    author: "George Eliot",
    genre: "english-literature",
    genreLabel: "English Literature",
    chunks: 4384,
    excerpt: "Tyke said they should have no more coals if they came to hear you preach.” Mrs. Farebrother laid down her knitting, which she had resumed after her small allowance of tea and toast, and looked at her son as if to say “You hear that?” Miss Noble said, “Oh poor things! poor…",
    tags: ["english-literature"],
  },
  {
    slug: "north_and_south_gaskell",
    title: "North and South (Gaskell)",
    author: "Elizabeth Cleghorn Gaskell",
    genre: "english-literature",
    genreLabel: "English Literature",
    chunks: 2409,
    excerpt: "The sharpness in her eye turned to a wistful longing as she met Margaret’s soft and friendly gaze. “I ha’ none so many to care for me; if yo’ care yo’ may come.” So they walked on together in silence. As they turned up into a small court, out of a squalid street, Bessy said,…",
    tags: ["english-literature"],
  },
  {
    slug: "pride_and_prejudice",
    title: "Pride and Prejudice",
    author: "Jane Austen",
    genre: "english-literature",
    genreLabel: "English Literature",
    chunks: 1773,
    excerpt: "Bennet’s expectations were fully answered. His cousin was as absurd as he had hoped; and he listened to him with the keenest enjoyment, maintaining at the same time the most resolute composure of countenance, and, except in an occasional glance at Elizabeth, requiring no…",
    tags: ["english-literature"],
  },
  {
    slug: "robinson_crusoe",
    title: "Robinson Crusoe",
    author: "Daniel Defoe",
    genre: "english-literature",
    genreLabel: "English Literature",
    chunks: 1435,
    excerpt: "I was not so much surprised with the lightning as I was with the thought which darted into my mind as swift as the lightning itself—Oh, my powder! My very heart sank within me when I thought that, at one blast, all my powder might be destroyed; on which, not my defence only,…",
    tags: ["english-literature"],
  },
  {
    slug: "sense_and_sensibility",
    title: "Sense and Sensibility",
    author: "Jane Austen",
    genre: "english-literature",
    genreLabel: "English Literature",
    chunks: 1656,
    excerpt: "My visits to Mrs. Smith are never repeated within the twelvemonth.” “And is Mrs. Smith your only friend? Is Allenham the only house in the neighbourhood to which you will be welcome? For shame, Willoughby, can you wait for an invitation here?” His colour increased; and with…",
    tags: ["english-literature"],
  },
  {
    slug: "tess_of_the_durbervilles_hardy",
    title: "Tess of the d'Urbervilles (Hardy)",
    author: "Thomas Hardy",
    genre: "english-literature",
    genreLabel: "English Literature",
    chunks: 2050,
    excerpt: "That’s more real than the other—hey? I have a little to do here at this stile.” The man turned, as he spoke, to an opening at the roadside leading into a pasture. “If you’ll wait a moment,” he added, “I shall not be long.” As he had her basket she could not well do otherwise;…",
    tags: ["english-literature"],
  },
  {
    slug: "the_adventures_of_sherlock_holmes",
    title: "The Adventures of Sherlock Holmes",
    author: "Arthur Conan Doyle",
    genre: "english-literature",
    genreLabel: "English Literature",
    chunks: 1366,
    excerpt: "That will just show you how fond he was of me, Mr. Holmes, and the little things that he would think of.” “It was most suggestive,” said Holmes. “It has long been an axiom of mine that the little things are infinitely the most important. Can you remember any other little…",
    tags: ["english-literature"],
  },
  {
    slug: "the_jungle_book_kipling",
    title: "The Jungle Book (Kipling)",
    author: "Rudyard Kipling",
    genre: "english-literature",
    genreLabel: "English Literature",
    chunks: 671,
    excerpt: "For a time he was afraid of being dropped. Then he grew angry but knew better than to struggle, and then he began to think. The first thing was to send back word to Baloo and Bagheera, for, at the pace the monkeys were going, he knew his friends would be left far behind. It…",
    tags: ["english-literature"],
  },
  {
    slug: "the_man_who_was_thursday_chesterton",
    title: "The Man Who Was Thursday (Chesterton)",
    author: "G. K. (Gilbert Keith) Chesterton",
    genre: "english-literature",
    genreLabel: "English Literature",
    chunks: 774,
    excerpt: "One of his uncles always walked about without a hat, and another had made an unsuccessful attempt to walk about with a hat and nothing else. His father cultivated art and self-realisation; his mother went in for simplicity and hygiene. Hence the child, during his tenderer…",
    tags: ["english-literature"],
  },
  {
    slug: "the_mayor_of_casterbridge_hardy",
    title: "The Mayor of Casterbridge (Hardy)",
    author: "Thomas Hardy",
    genre: "english-literature",
    genreLabel: "English Literature",
    chunks: 1599,
    excerpt: "Henchard preceded her through the door in the wall to the suddenly changed scene of the garden and flowers, and onward into the house. The dining-room to which he introduced her still exhibited the remnants of the lavish breakfast laid for Farfrae. It was furnished to…",
    tags: ["english-literature"],
  },
  {
    slug: "the_picture_of_dorian_gray",
    title: "The Picture of Dorian Gray",
    author: "Oscar Wilde",
    genre: "english-literature",
    genreLabel: "English Literature",
    chunks: 1010,
    excerpt: "In fact I consider you extremely dangerous, and if anything happens to our good duchess, we shall all look on you as being primarily responsible. But I should like to talk to you about life. The generation into which I was born was tedious. Some day, when you are tired of…",
    tags: ["english-literature"],
  },
  {
    slug: "the_portrait_of_a_lady_volume_1",
    title: "The Portrait of a Lady — Volume 1",
    author: "Henry James",
    genre: "english-literature",
    genreLabel: "English Literature",
    chunks: 1611,
    excerpt: "I infer also that you like my mother.” “I like your mother very much, because--because--” And Isabel found herself attempting to assign a reason for her affection for Mrs. Touchett. “Ah, we never know why!” said her companion, laughing. “I always know why,” the girl answered.…",
    tags: ["english-literature"],
  },
  {
    slug: "the_portrait_of_a_lady_volume_2",
    title: "The Portrait of a Lady — Volume 2",
    author: "Henry James",
    genre: "english-literature",
    genreLabel: "English Literature",
    chunks: 1494,
    excerpt: "But I care myself if I tell fibs; I never tell them unless there’s something rather good to be gained. I don’t see what’s to be gained with you--especially as you wouldn’t believe me. I don’t make professions any more than I make paper flowers or flouncey lampshades--I don’t…",
    tags: ["english-literature"],
  },
  {
    slug: "the_strange_case_of_dr_jekyll_and_mr_hyde",
    title: "The Strange Case of Dr Jekyll and Mr Hyde",
    author: "Robert Louis Stevenson",
    genre: "english-literature",
    genreLabel: "English Literature",
    chunks: 352,
    excerpt: "The last, I think; for, O my poor old Harry Jekyll, if ever I read Satan’s signature upon a face, it is on that of your new friend.” Round the corner from the by-street, there was a square of ancient, handsome houses, now for the most part decayed from their high estate and…",
    tags: ["english-literature"],
  },
  {
    slug: "the_time_machine",
    title: "The Time Machine",
    author: "H. G. (Herbert George) Wells",
    genre: "english-literature",
    genreLabel: "English Literature",
    chunks: 433,
    excerpt: "What strange developments of humanity, what wonderful advances upon our rudimentary civilisation, I thought, might not appear when I came to look nearly into the dim elusive world that raced and fluctuated before my eyes! I saw great and splendid architecture rising about me,…",
    tags: ["english-literature"],
  },
  {
    slug: "the_turn_of_the_screw_henry_james",
    title: "The Turn of the Screw (Henry James)",
    author: "Henry James",
    genre: "english-literature",
    genreLabel: "English Literature",
    chunks: 565,
    excerpt: "Grose. This picture comes back to me in the general train—the impression, as I received it on my return, of the wide white panelled space, bright in the lamplight and with its portraits and red carpet, and of the good surprised look of my friend, which immediately told me she…",
    tags: ["english-literature"],
  },
  {
    slug: "the_war_of_the_worlds",
    title: "The War of the Worlds",
    author: "H. G. (Herbert George) Wells",
    genre: "english-literature",
    genreLabel: "English Literature",
    chunks: 812,
    excerpt: "Close on the heels of that came a violent rattling crash, quite close to us, that shook the ground; and, starting out upon the lawn, I saw the tops of the trees about the Oriental College burst into smoky red flame, and the tower of the little church beside it slide down into…",
    tags: ["english-literature"],
  },
  {
    slug: "treasure_island",
    title: "Treasure Island",
    author: "Robert Louis Stevenson",
    genre: "english-literature",
    genreLabel: "English Literature",
    chunks: 886,
    excerpt: "They go the length of declaring that this honest creature would do anything for money, that the HISPANIOLA belonged to him, and that he sold it me absurdly high--the most transparent calumnies. None of them dare, however, to deny the merits of the ship. So far there was not a…",
    tags: ["english-literature"],
  },
  {
    slug: "vanity_fair_thackeray",
    title: "Vanity Fair (Thackeray)",
    author: "William Makepeace Thackeray",
    genre: "english-literature",
    genreLabel: "English Literature",
    chunks: 4146,
    excerpt: "\"Vamous,\" said Sir Pitt. \"Who'd ha' thought it! what a sly little devil! what a little fox it waws!\" he muttered to himself, chuckling with pleasure. \"Who'd have thought what?\" cries Miss Crawley, stamping with her foot. \"Pray, Miss Sharp, are you waiting for the Prince…",
    tags: ["english-literature"],
  },
  {
    slug: "wuthering_heights",
    title: "Wuthering Heights",
    author: "Emily Brontë",
    genre: "english-literature",
    genreLabel: "English Literature",
    chunks: 1588,
    excerpt: "His childhood’s sense of superiority, instilled into him by the favours of old Mr. Earnshaw, was faded away. He struggled long to keep up an equality with Catherine in her studies, and yielded with poignant though silent regret: but he yielded completely; and there was no…",
    tags: ["english-literature"],
  },
  {
    slug: "around_the_world_in_eighty_days_verne",
    title: "Around the World in Eighty Days (Verne)",
    author: "Jules Verne",
    genre: "french-literature",
    genreLabel: "French Literature",
    chunks: 887,
    excerpt: "It happened to be the day of a Parsee festival. These descendants of the sect of Zoroaster—the most thrifty, civilised, intelligent, and austere of the East Indians, among whom are counted the richest native merchants of Bombay—were celebrating a sort of religious carnival,…",
    tags: ["french-literature"],
  },
  {
    slug: "candide",
    title: "Candide",
    author: "Voltaire",
    genre: "french-literature",
    genreLabel: "French Literature",
    chunks: 486,
    excerpt: "In three months time, having lost all his money, and being grown tired of my company, he sold me to a Jew, named Don Issachar, who traded to Holland and Portugal, and had a strong passion for women. This Jew was much attached to my person, but could not triumph over it; I…",
    tags: ["french-literature"],
  },
  {
    slug: "from_the_earth_to_the_moon_verne",
    title: "From the Earth to the Moon (Verne)",
    author: "Jules Verne",
    genre: "french-literature",
    genreLabel: "French Literature",
    chunks: 1265,
    excerpt: "Russia paid in as her contingent the enormous sum of 368,733 roubles. No one need be surprised at this, who bears in mind the scientific taste of the Russians, and the impetus which they have given to astronomical studies—thanks to their numerous observatories. France began…",
    tags: ["french-literature"],
  },
  {
    slug: "germinal",
    title: "Germinal",
    author: "Émile Zola",
    genre: "french-literature",
    genreLabel: "French Literature",
    chunks: 2381,
    excerpt: "For a moment the schoolmaster's pale head was also seen behind the school-house hedge. Among the gardens, the man who was digging stood with one foot on his spade, and with rounded eyes. And the murmur of gossiping gradually increased, with a sound of rattles, like a gust of…",
    tags: ["french-literature"],
  },
  {
    slug: "journey_to_the_center_of_the_earth_verne",
    title: "Journey to the Center of the Earth (Verne)",
    author: "Jules Verne",
    genre: "french-literature",
    genreLabel: "French Literature",
    chunks: 998,
    excerpt: "\"I shall be dizzy,\" I said. \"The more reason why we should go up; we must get used to it.\" \"But--\" \"Come, I tell you; don't waste our time.\" I had to obey. A keeper who lived at the other end of the street handed us the key, and the ascent began. My uncle went ahead with a…",
    tags: ["french-literature"],
  },
  {
    slug: "les_miserables",
    title: "Les Miserables",
    author: "Victor Hugo",
    genre: "french-literature",
    genreLabel: "French Literature",
    chunks: 7636,
    excerpt: "When you are reasonable, I will bring her to you myself.” The poor mother bowed her head. “I beg your pardon, doctor, I really beg your pardon. Formerly I should never have spoken as I have just done; so many misfortunes have happened to me, that I sometimes do not know what…",
    tags: ["french-literature"],
  },
  {
    slug: "madame_bovary",
    title: "Madame Bovary",
    author: "Gustave Flaubert",
    genre: "french-literature",
    genreLabel: "French Literature",
    chunks: 1583,
    excerpt: "Then he wrote to the chemist of the place to ask the number of the population, the distance from the nearest doctor, what his predecessor had made a year, and so forth; and the answer being satisfactory, he made up his mind to move towards the spring, if Emma’s health did not…",
    tags: ["french-literature"],
  },
  {
    slug: "nana_zola",
    title: "Nana (Zola)",
    author: "Émile Zola",
    genre: "french-literature",
    genreLabel: "French Literature",
    chunks: 2062,
    excerpt: "Dans ces cas-là, par exemple, il se mettait en travers. Et, les mains belles, un diamant au petit doigt, il achevait un filet de chevreuil. D'ailleurs, la conversation sur les enfants continuait. La Faloise, empli de trouble par le voisinage de Gaga, lui demandait des…",
    tags: ["french-literature"],
  },
  {
    slug: "the_count_of_monte_cristo",
    title: "The Count of Monte Cristo",
    author: "Auguste Maquet",
    genre: "french-literature",
    genreLabel: "French Literature",
    chunks: 5744,
    excerpt: "But you tell me he is no more, and therefore can have nothing to do with hatred or revenge, so let all such feeling be buried with him.” “You prefer, then,” said the abbé, “that I should bestow on men you say are false and treacherous, the reward intended for faithful…",
    tags: ["french-literature"],
  },
  {
    slug: "the_hunchback_of_notre_dame_hugo",
    title: "The Hunchback of Notre-Dame (Hugo)",
    author: "Victor Hugo",
    genre: "french-literature",
    genreLabel: "French Literature",
    chunks: 2517,
    excerpt: "Was it not Louis XIV., fulfilling the request of Louis XIII.? And who put the cold, white panes in the place of those windows, “high in color,” which caused the astonished eyes of our fathers to hesitate between the rose of the grand portal and the arches of the apse? And…",
    tags: ["french-literature"],
  },
  {
    slug: "the_three_musketeers",
    title: "The Three Musketeers",
    author: "Auguste Maquet",
    genre: "french-literature",
    genreLabel: "French Literature",
    chunks: 2988,
    excerpt: "D’Artagnan resolved to try and enter the Louvre. His costume of Guardsman in the company of M. Dessessart ought to be his passport. He therefore went down the Rue des Petits Augustins, and came up to the quay, in order to take the New Bridge. He had at first an idea of…",
    tags: ["french-literature"],
  },
];
