import type { Book } from "./catalogTypes";

export const BOOKS_PART1: Book[] = [
  {
    slug: "adventures_of_huckleberry_finn",
    title: "Adventures of Huckleberry Finn",
    author: "Mark Twain",
    genre: "american-literature",
    genreLabel: "American Literature",
    chunks: 1362,
    excerpt: "Does three hundred dollars lay around every day for people to pick up? Some folks think the nigger ain’t far from here. I’m one of them—but I hain’t talked it around. A few days ago I was talking with an old couple that lives next door in the log shanty, and they happened to…",
    tags: ["american-literature"],
  },
  {
    slug: "ebony_and_crystal_poems_in_verse_and_prose",
    title: "Ebony and Crystal: Poems in Verse and Prose",
    author: "Clark Ashton Smith",
    genre: "american-literature",
    genreLabel: "American Literature",
    chunks: 388,
    excerpt: "Desolate oceans, and the light of lonely plains, Dead moons that wander in the wastes of ice and snow— These, these I fain would see, and find the splendid bourne Of sunset, or the brazen deserts of the morn, That I might lose this ever-aching loneliness In vaster solitude;…",
    tags: ["american-literature"],
  },
  {
    slug: "leaves_of_grass",
    title: "Leaves of Grass",
    author: "Walt Whitman",
    genre: "american-literature",
    genreLabel: "American Literature",
    chunks: 1346,
    excerpt: "To have the gag remov’d from one’s mouth! To have the feeling to-day or any day I am sufficient as I am. O something unprov’d! something in a trance! To escape utterly from others’ anchors and holds! To drive free! to love free! to dash reckless and dangerous! To court…",
    tags: ["american-literature"],
  },
  {
    slug: "moby_dick",
    title: "Moby Dick",
    author: "Herman Melville",
    genre: "american-literature",
    genreLabel: "American Literature",
    chunks: 2922,
    excerpt: "And who composed the first narrative of a whaling-voyage? Who, but no less a prince than Alfred the Great, who, with his own royal pen, took down the words from Other, the Norwegian whale-hunter of those times! And who pronounced our glowing eulogy in Parliament? Who, but…",
    tags: ["american-literature"],
  },
  {
    slug: "my_antonia_cather",
    title: "My Antonia (Cather)",
    author: "Willa Cather",
    genre: "american-literature",
    genreLabel: "American Literature",
    chunks: 1038,
    excerpt: "When the triplets were taken ashore at New York, he had, as he said, ‘to carry some of them.’ The trip to Chicago was even worse than the ocean voyage. On the train it was very difficult to get milk for the babies and to keep their bottles clean. The mother did her best, but…",
    tags: ["american-literature"],
  },
  {
    slug: "o_pioneers_cather",
    title: "O Pioneers! (Cather)",
    author: "Willa Cather",
    genre: "american-literature",
    genreLabel: "American Literature",
    chunks: 718,
    excerpt: "Linstrum. They couldn’t get ahead even in good years, and they all got into debt while father was getting out. I think we ought to hold on as long as we can on father’s account. He was so set on keeping this land. He must have seen harder times than this, here. How was it in…",
    tags: ["american-literature"],
  },
  {
    slug: "tales_of_mystery_and_imagination_poe",
    title: "Tales of Mystery and Imagination (Poe)",
    author: "Edgar Allan Poe",
    genre: "american-literature",
    genreLabel: "American Literature",
    chunks: 1262,
    excerpt: "Thus I found that my senses would shortly give way altogether, and I had already clutched one of the valve ropes with the view of attempting a descent, when the recollection of the trick I had played the three creditors, and the possible consequences to myself, should I…",
    tags: ["american-literature"],
  },
  {
    slug: "the_age_of_innocence_wharton",
    title: "The Age of Innocence (Wharton)",
    author: "Edith Wharton",
    genre: "american-literature",
    genreLabel: "American Literature",
    chunks: 1409,
    excerpt: "He tried to analyse the trick, to find a clue to it in the way the chairs and tables were grouped, in the fact that only two Jacqueminot roses (of which nobody ever bought less than a dozen) had been placed in the slender vase at his elbow, and in the vague pervading perfume…",
    tags: ["american-literature"],
  },
  {
    slug: "the_awakening_chopin",
    title: "The Awakening (Chopin)",
    author: "Kate Chopin",
    genre: "american-literature",
    genreLabel: "American Literature",
    chunks: 858,
    excerpt: "Perhaps he will never wholly release her from the spell. Perhaps she will never again suffer a poor, unworthy earthling to walk in the shadow of her divine presence.” “Don’t banter me,” she said, wounded at what appeared to be his flippancy. He did not mind the entreaty, but…",
    tags: ["american-literature"],
  },
  {
    slug: "the_call_of_the_wild",
    title: "The Call of the Wild",
    author: "Jack London",
    genre: "american-literature",
    genreLabel: "American Literature",
    chunks: 417,
    excerpt: "They made good time down the chain of lakes which fills the craters of extinct volcanoes, and late that night pulled into the huge camp at the head of Lake Bennett, where thousands of goldseekers were building boats against the break-up of the ice in the spring. Buck made his…",
    tags: ["american-literature"],
  },
  {
    slug: "the_house_of_mirth_wharton",
    title: "The House of Mirth (Wharton)",
    author: "Edith Wharton",
    genre: "american-literature",
    genreLabel: "American Literature",
    chunks: 1788,
    excerpt: "But perhaps it’s rather that I never had any choice. There was no one, I mean, to tell me about the republic of the spirit.” “There never is—it’s a country one has to find the way to one’s self.” “But I should never have found my way there if you hadn’t told me.” “Ah, there…",
    tags: ["american-literature"],
  },
  {
    slug: "the_jungle_sinclair",
    title: "The Jungle (Sinclair)",
    author: "Upton Sinclair",
    genre: "american-literature",
    genreLabel: "American Literature",
    chunks: 1953,
    excerpt: "He had gone all to ruin with the drink, however, and lost his power; one of his sons, who was a good man, had kept him and the family up for a year or two, but then he had got sick with consumption. That was another thing, Grandmother Majauszkiene interrupted herself—this…",
    tags: ["american-literature"],
  },
  {
    slug: "the_legend_of_sleepy_hollow_irving",
    title: "The Legend of Sleepy Hollow (Irving)",
    author: "Washington Irving",
    genre: "american-literature",
    genreLabel: "American Literature",
    chunks: 177,
    excerpt: "Thus, by divers little makeshifts, in that ingenious way which is commonly denominated “by hook and by crook,” the worthy pedagogue got on tolerably enough, and was thought, by all who understood nothing of the labor of headwork, to have a wonderfully easy life of it.",
    tags: ["american-literature"],
  },
  {
    slug: "the_raven_and_other_poems_poe",
    title: "The Raven and Other Poems (Poe)",
    author: "Edgar Allan Poe",
    genre: "american-literature",
    genreLabel: "American Literature",
    chunks: 102,
    excerpt: "One by one they sound, like the chiming of the brazen and ebony clock, in \"The Masque of the Red Death,\" which made the waltzers pause with \"disconcert and tremulousness and meditation,\" as often as the hour came round. Of all these mystical cadences, the plaint of _The…",
    tags: ["american-literature"],
  },
  {
    slug: "the_red_badge_of_courage",
    title: "The Red Badge of Courage",
    author: "Stephen Crane",
    genre: "american-literature",
    genreLabel: "American Literature",
    chunks: 603,
    excerpt: "The strain of present circumstances he felt to be intolerable. The philosophical tall soldier measured a sandwich of cracker and pork and swallowed it in a nonchalant manner. “Oh, I suppose we must go reconnoitering around the country jest to keep ’em from getting too close,…",
    tags: ["american-literature"],
  },
  {
    slug: "the_scarlet_letter",
    title: "The Scarlet Letter",
    author: "Nathaniel Hawthorne",
    genre: "american-literature",
    genreLabel: "American Literature",
    chunks: 1219,
    excerpt: "Madame Hester would have winced at that, I warrant me. But she—the naughty baggage—little will she care what they put upon the bodice of her gown!",
    tags: ["american-literature"],
  },
  {
    slug: "the_sea_wolf",
    title: "The Sea-Wolf",
    author: "Jack London",
    genre: "american-literature",
    genreLabel: "American Literature",
    chunks: 1382,
    excerpt: "And ever out of the north-east the brave wind blows, driving us on our course two hundred and fifty miles between the dawns. It saddens me and gladdens me, the gait with which we are leaving San Francisco behind and with which we are foaming down upon the tropics. Each day…",
    tags: ["american-literature"],
  },
  {
    slug: "the_souls_of_black_folk_du_bois",
    title: "The Souls of Black Folk (Du Bois)",
    author: "W. E. B. (William Edward Burghardt) Du Bois",
    genre: "american-literature",
    genreLabel: "American Literature",
    chunks: 973,
    excerpt: "Naturally the Negroes resented, at first bitterly, signs of compromise which surrendered their civil and political rights, even though this was to be exchanged for larger chances of economic development. The rich and dominating North, however, was not only weary of the race…",
    tags: ["american-literature"],
  },
  {
    slug: "the_star_treader_and_other_poems",
    title: "The Star-Treader, and other poems",
    author: "Clark Ashton Smith",
    genre: "american-literature",
    genreLabel: "American Literature",
    chunks: 202,
    excerpt: "What spheres that now essay Time's undimensioned vast, Shall plunge forgotten to thy gloom at length, With life that cried its query of the Night To ears with silence filled! What worlds unborn shall dare thy strength, Girt by a sun's unwearied might, And dip to darkness when…",
    tags: ["american-literature"],
  },
  {
    slug: "the_yellow_wallpaper",
    title: "The Yellow Wallpaper",
    author: "Charlotte Perkins Gilman",
    genre: "american-literature",
    genreLabel: "American Literature",
    chunks: 77,
    excerpt: "He said we came here solely on my account, that I was to have perfect rest and all the air I could get. “Your exercise depends on your strength, my dear,” said he, “and your food somewhat on your appetite; but air you can absorb all the time.” So we took the nursery, at the…",
    tags: ["american-literature"],
  },
  {
    slug: "uncle_toms_cabin",
    title: "Uncle Toms Cabin",
    author: "Harriet Beecher Stowe",
    genre: "american-literature",
    genreLabel: "American Literature",
    chunks: 2416,
    excerpt: "It took no inconsiderable perseverance to arouse the inmates; but at last the respectable proprietor appeared, and undid the door. He was a great, tall, bristling Orson of a fellow, full six feet and some inches in his stockings, and arrayed in a red flannel hunting-shirt. A…",
    tags: ["american-literature"],
  },
  {
    slug: "walden",
    title: "Walden",
    author: "Henry David Thoreau",
    genre: "american-literature",
    genreLabel: "American Literature",
    chunks: 1522,
    excerpt: "There are those who have used all their arts to persuade me to undertake the support of some poor family in the town; and if I had nothing to do,—for the devil finds employment for the idle,—I might try my hand at some such pastime as that.",
    tags: ["american-literature"],
  },
  {
    slug: "white_fang_london",
    title: "White Fang (London)",
    author: "Jack London",
    genre: "american-literature",
    genreLabel: "American Literature",
    chunks: 937,
    excerpt: "He could resist the call of the world no longer. Besides, he was hungry. He crawled over to his mate and tried to persuade her to get up. But she only snarled at him, and he walked out alone into the bright sunshine to find the snow-surface soft under foot and the travelling…",
    tags: ["american-literature"],
  },
  {
    slug: "a_selection_from_the_discourses_of_epictetus_with_the_enchei",
    title: "A Selection from the Discourses of Epictetus with the Encheiridion",
    author: "Epictetus",
    genre: "ancient-classical",
    genreLabel: "Ancient & Classical",
    chunks: 791,
    excerpt: "It is shameful for philosophers thus to contemplate the works of nature. For what is a master? Man is not the master of man; but death is, and life and pleasure and pain; for if he comes without these things, bring Cæsar to me and you will see how firm I am. But when he shall…",
    tags: ["ancient-classical"],
  },
  {
    slug: "histories_herodotus",
    title: "Histories (Herodotus)",
    author: "Herodotus",
    genre: "ancient-classical",
    genreLabel: "Ancient & Classical",
    chunks: 1981,
    excerpt: "For this reason then the Ionians also made for themselves twelve cities; for at any rate to say that these are any more Ionians than the other Ionians, or have at all a nobler descent, is mere folly, considering that a large part of them are Abantians from Euboea, who have no…",
    tags: ["ancient-classical"],
  },
  {
    slug: "history_of_the_peloponnesian_war_thucydides",
    title: "History of the Peloponnesian War (Thucydides)",
    author: "Thucydides",
    genre: "ancient-classical",
    genreLabel: "Ancient & Classical",
    chunks: 2965,
    excerpt: "And it is only the Athenians, who, fearless of consequences, confer their benefits not from calculations of expediency, but in the confidence of liberality. “In short, I say that as a city we are the school of Hellas, while I doubt if the world can produce a man who, where he…",
    tags: ["ancient-classical"],
  },
  {
    slug: "medea_of_euripides",
    title: "Medea of Euripides",
    author: "Euripides",
    genre: "ancient-classical",
    genreLabel: "Ancient & Classical",
    chunks: 275,
    excerpt: "The feast hath filled them: all is well! _Others._ I heard a song, but it comes no more. Where the tears ran over: A keen cry but tired, tired: A woman's cry for her heart's desired, For a traitor's kiss and a lost lover. But a prayer, methinks, yet riseth sore To God, to…",
    tags: ["ancient-classical"],
  },
  {
    slug: "metamorphoses_ovid",
    title: "Metamorphoses (Ovid)",
    author: "Ovid",
    genre: "ancient-classical",
    genreLabel: "Ancient & Classical",
    chunks: 1757,
    excerpt: "Soon as the son of Clymene had arrived thither by an ascending path, and entered the house of his parent, {thus} doubted of; he immediately turned his steps to the presence of his father, and stood at a distance, for he could not bear the refulgence nearer. Arrayed in a…",
    tags: ["ancient-classical"],
  },
  {
    slug: "minor_dialogues_together_with_the_dialogue_on_clemency",
    title: "Minor Dialogues, Together With the Dialogue on Clemency",
    author: "Lucius Annaeus Seneca",
    genre: "ancient-classical",
    genreLabel: "Ancient & Classical",
    chunks: 1976,
    excerpt: "Now, no sane man is angry with nature: for what should we say if a man chose to be surprised that fruit did not hang on the thickets of a forest, or to wonder at bushes and thorns not being covered with some useful berry? No one is angry when nature excuses a defect.",
    tags: ["ancient-classical"],
  },
  {
    slug: "oedipus_king_of_thebes",
    title: "Oedipus King of Thebes",
    author: "Sophocles",
    genre: "ancient-classical",
    genreLabel: "Ancient & Classical",
    chunks: 243,
    excerpt: "OEDIPUS. And what was that? One thing has often brought Others, could we but catch one little clue. CREON. 'Twas not one man, 'twas robbers--that he knew-- Who barred the road and slew him: a great band. OEDIPUS. Robbers?... What robber, save the work was planned By treason…",
    tags: ["ancient-classical"],
  },
  {
    slug: "on_the_nature_of_things_lucretius",
    title: "On the Nature of Things (Lucretius)",
    author: "Titus Lucretius Carus",
    genre: "ancient-classical",
    genreLabel: "Ancient & Classical",
    chunks: 1019,
    excerpt: "Lastly, whatso thou markest to disperse Upon the instant--smoke, and cloud, and flame-- Must not (even though not all of smooth and round) Be yet co-linked with atoms intertwined, That thus they can, without together cleaving, So pierce our body and so bore the rocks.…",
    tags: ["ancient-classical"],
  },
  {
    slug: "parallel_lives_plutarch",
    title: "Parallel Lives (Plutarch)",
    author: "Plutarch",
    genre: "ancient-classical",
    genreLabel: "Ancient & Classical",
    chunks: 10353,
    excerpt: "As, indeed, there came no good of it; for the tribunes, who were present, perceiving how the proposal of Marcius took, ran out into the crowd with exclamations, calling on the plebeians to stand together, and come in to their assistance. The assembly met, and soon became…",
    tags: ["ancient-classical"],
  },
  {
    slug: "the_aeneid",
    title: "The Aeneid",
    author: "Virgil",
    genre: "ancient-classical",
    genreLabel: "Ancient & Classical",
    chunks: 1509,
    excerpt: "Far on the right, her dogs foul Scylla hides: Charybdis roaring on the left presides, And in her greedy whirlpool sucks the tides; Then spouts them from below: with fury driv’n, The waves mount up and wash the face of heav’n. But Scylla from her den, with open jaws, The…",
    tags: ["ancient-classical"],
  },
  {
    slug: "the_birds_aristophanes",
    title: "The Birds (Aristophanes)",
    author: "Aristophanes",
    genre: "ancient-classical",
    genreLabel: "Ancient & Classical",
    chunks: 287,
    excerpt: "PISTHETAERUS What for? EUELPIDES Epops is going to sing again. EPOPS (IN THE COPPICE) Epopoi poi popoi, epopoi, popoi, here, here, quick, quick, quick, my comrades in the air; all you who pillage the fertile lands of the husbandmen, the numberless tribes who gather and devour…",
    tags: ["ancient-classical"],
  },
  {
    slug: "the_clouds_aristophanes",
    title: "The Clouds (Aristophanes)",
    author: "Aristophanes",
    genre: "ancient-classical",
    genreLabel: "Ancient & Classical",
    chunks: 203,
    excerpt: "Soc. It becomes the old man to speak words of good omen, and to hearken to my prayer. O sovereign King, immeasurable Air, who keepest the earth suspended, and through bright Aether, and ye august goddesses, the Clouds, sending thunder and lightning, arise, appear in the air,…",
    tags: ["ancient-classical"],
  },
  {
    slug: "the_consolation_of_philosophy_boethius",
    title: "The Consolation of Philosophy (Boethius)",
    author: "Boethius",
    genre: "ancient-classical",
    genreLabel: "Ancient & Classical",
    chunks: 597,
    excerpt: "She who still veils herself from others hath fully discovered to thee her whole character. If thou likest her, take her as she is, and do not complain. If thou abhorrest her perfidy, turn from her in disdain, renounce her, for baneful are her delusions. The very thing which…",
    tags: ["ancient-classical"],
  },
  {
    slug: "the_eleven_comedies_volume_1",
    title: "The Eleven Comedies, Volume 1",
    author: "Aristophanes",
    genre: "ancient-classical",
    genreLabel: "Ancient & Classical",
    chunks: 1183,
    excerpt: "SAUSAGE-SELLER. I will undertake that, and in three days too! But listen to this further oracle, by which Apollo puts you on your guard against the snares of the greedy fist. DEMOS. Of what greedy fist? SAUSAGE-SELLER. The god in this oracle very clearly points to the hand of…",
    tags: ["ancient-classical"],
  },
  {
    slug: "the_eleven_comedies_volume_2",
    title: "The Eleven Comedies, Volume 2",
    author: "Aristophanes",
    genre: "ancient-classical",
    genreLabel: "Ancient & Classical",
    chunks: 1380,
    excerpt: "PISTHETAERUS. By Zeus, it no longer croaks the same thing it did. EUELPIDES. And which way does it tell us to go now? PISTHETAERUS. It says that, by dint of gnawing, it will devour my fingers. EUELPIDES. What misfortune is ours! we strain every nerve to get to the birds,[179]…",
    tags: ["ancient-classical"],
  },
  {
    slug: "the_frogs",
    title: "The Frogs",
    author: "Aristophanes",
    genre: "ancient-classical",
    genreLabel: "Ancient & Classical",
    chunks: 186,
    excerpt: "DIO. This timing song I take from you. FR. That's a dreadful thing to do. DIO. Much more dreadful, if I row Till I burst myself, I trow. FR. and DIO. Brekekekex, ko-ax, ko-ax. DIO. Go, hang yourselves; for what care I? FR. All the same we'll shout and cry, Stretching all our…",
    tags: ["ancient-classical"],
  },
  {
    slug: "the_golden_sayings_of_epictetus_with_the_hymn_of_cleanthes",
    title: "The Golden Sayings of Epictetus, with the Hymn of Cleanthes",
    author: "Epictetus",
    genre: "ancient-classical",
    genreLabel: "Ancient & Classical",
    chunks: 360,
    excerpt: "Has a man been raised to tribuneship? Every one that he meets congratulates him. One kisses him on the eyes, another on the neck, while the slaves kiss his hands. He goes home to find torches burning; he ascends to the Capitol to sacrifice.—Who ever sacrificed for having had…",
    tags: ["ancient-classical"],
  },
  {
    slug: "the_house_of_atreus_being_the_agamemnon_the_libation_bearers",
    title: "The House of Atreus; Being the Agamemnon, the Libation bearers, and the Furies",
    author: "Aeschylus",
    genre: "ancient-classical",
    genreLabel: "Ancient & Classical",
    chunks: 585,
    excerpt: "And still the smoke of fallen Ilion Rises in sight of all men, and the flame Of Atè’s hecatomb is living yet, And where the towers in dusty ashes sink, Rise the rich fumes of pomp and wealth consumed. For this must all men pay unto the gods The meed of mindful hearts and…",
    tags: ["ancient-classical"],
  },
  {
    slug: "the_iliad",
    title: "The Iliad",
    author: "Homer",
    genre: "ancient-classical",
    genreLabel: "Ancient & Classical",
    chunks: 2706,
    excerpt: "“Haste, happy nymph! for thee thy Paris calls, Safe from the fight, in yonder lofty walls, Fair as a god; with odours round him spread, He lies, and waits thee on the well-known bed; Not like a warrior parted from the foe, But some gay dancer in the public show.” She spoke,…",
    tags: ["ancient-classical"],
  },
  {
    slug: "the_meditations_of_the_emperor_marcus_aurelius_antoninus",
    title: "The Meditations of the Emperor Marcus Aurelius Antoninus",
    author: "Emperor of Rome Marcus Aurelius",
    genre: "ancient-classical",
    genreLabel: "Ancient & Classical",
    chunks: 542,
    excerpt: "Behold the chaos of eternity which besets us on either side. Think how empty is the noisy echo of acclamation; how fickle and how scant of judgment are they who would seem to praise us, and how narrow the bounds within which their praise is confined. All the earth is but a…",
    tags: ["ancient-classical"],
  },
];
