import type { Book } from "./catalogTypes";

export const BOOKS_PART2: Book[] = [
  {
    slug: "the_odyssey",
    title: "The Odyssey",
    author: "Homer",
    genre: "ancient-classical",
    genreLabel: "Ancient & Classical",
    chunks: 1668,
    excerpt: "I will also give you clothes, and will send you a fair wind to take you home, if the gods in heaven so will it—for they know more about these things, and can settle them better than I can.” Ulysses shuddered as he heard her. “Now goddess,” he answered, “there is something…",
    tags: ["ancient-classical"],
  },
  {
    slug: "the_teaching_of_epictetus",
    title: "The Teaching of Epictetus",
    author: "Epictetus",
    genre: "ancient-classical",
    genreLabel: "Ancient & Classical",
    chunks: 876,
    excerpt: "And when is a disjunctive safe? When it fulfills its promise. And when are flutes, or a lyre, or a horse, or a dog? What marvel is it, then, if a man also is to be saved in the same way, and perish in the same way? 6. But each thing is increased and saved by the corresponding…",
    tags: ["ancient-classical"],
  },
  {
    slug: "thoughts_of_marcus_aurelius_antoninus",
    title: "Thoughts of Marcus Aurelius Antoninus",
    author: "Emperor of Rome Marcus Aurelius",
    genre: "ancient-classical",
    genreLabel: "Ancient & Classical",
    chunks: 1016,
    excerpt: "I would have all men think as they please, or as they can, and I only claim the same freedom which I give. When a man writes anything, we may fairly try to find out all that his words must mean, even if the result is that they mean what he did not mean; and if we find this…",
    tags: ["ancient-classical"],
  },
  {
    slug: "audels_electric_library_vol_1",
    title: "Audels Electric Library Vol 1",
    author: "Unknown",
    genre: "audel-electric",
    genreLabel: "Technical Reference",
    chunks: 1610,
    excerpt: "Wes bari Be | TE fe eae | Pre Sn He Ny! H.Ba&kCaly fli | . ° = AT) er ae iyyy.t a tar py Cag Gave Wig oa a a carre Sh : ' myn (00% . . : J on wi H u ' agra , HP ye oh ) ni oN aye ta he My ae iy\" oe t 1 Ke feng : | | i ' in | rr we av Pe Le opie Tart | i 7 as ae AF To nf : at…",
    tags: ["audel-electric"],
  },
  {
    slug: "audels_electric_library_vol_10",
    title: "Audels Electric Library Vol 10",
    author: "Unknown",
    genre: "audel-electric",
    genreLabel: "Technical Reference",
    chunks: 2433,
    excerpt: "Fit the dynamo to the job and not the job to the dynamo. Fic. 8,244.—Reliance armature with double commutator Scientifically metered control of deposit is becoming more and more customary and scientific regulation of the plating dynamo must be equally exact. Series rheostats…",
    tags: ["audel-electric"],
  },
  {
    slug: "audels_electric_library_vol_2",
    title: "Audels Electric Library Vol 2",
    author: "Unknown",
    genre: "audel-electric",
    genreLabel: "Technical Reference",
    chunks: 1521,
    excerpt: "Fie. 780.—Typical shaft for an armature. The illustration shows the keyways for pulley, armature and commutator. In the smaller sizes, there is usually a flange at A, and threads at B and C, for retaining nuts. The shaft is subject also to bending by the weight of the…",
    tags: ["audel-electric"],
  },
  {
    slug: "audels_electric_library_vol_3",
    title: "Audels Electric Library Vol 3",
    author: "Unknown",
    genre: "audel-electric",
    genreLabel: "Technical Reference",
    chunks: 1742,
    excerpt: "Fie. 1,443 —Method of polishing Duncan commutator with tape. | erian Bove ; | at Kies. 1,444 to 1,446.—Duncan meter showing method of replacing fixed type compensating coil with swinging type. R, red lead to positive series binding post if 110 volt m. ter; if 220 volt meter,…",
    tags: ["audel-electric"],
  },
  {
    slug: "audels_electric_library_vol_4",
    title: "Audels Electric Library Vol 4",
    author: "Unknown",
    genre: "audel-electric",
    genreLabel: "Technical Reference",
    chunks: 1660,
    excerpt: ": [OYTYOY OY) | < , fe a) 3 MAIN anes (O} > > «=D a> a= am 4",
    tags: ["audel-electric"],
  },
  {
    slug: "audels_electric_library_vol_7",
    title: "Audels Electric Library Vol 7",
    author: "Unknown",
    genre: "audel-electric",
    genreLabel: "Technical Reference",
    chunks: 2370,
    excerpt: "Example.—Ninety-one 16 candle power lamps consuming 3.1 watts per candle power at a pressure of 110 volts, will-require a current of 163.191 'The distance from the entrance cut out to the main or feeder switch is 200 feet, then for a 2 per cent. drop, or a loss of 110.02 =2.2…",
    tags: ["audel-electric"],
  },
  {
    slug: "audels_electric_library_vol_8",
    title: "Audels Electric Library Vol 8",
    author: "Unknown",
    genre: "audel-electric",
    genreLabel: "Technical Reference",
    chunks: 2845,
    excerpt: "Furthermore, this results in a delayed release and a waste of air. _ Under normal operating conditions an equalizing point corresponds to a reduction of 20 lbs. from 70 lbs. brake pipe pressure. The brake pipe reduc- tion is automatically limited when operating electrically…",
    tags: ["audel-electric"],
  },
  {
    slug: "audels_electric_library_vol_9",
    title: "Audels Electric Library Vol 9",
    author: "Unknown",
    genre: "audel-electric",
    genreLabel: "Technical Reference",
    chunks: 2191,
    excerpt: "If the diaphragm become saturated zt will not respond perfectly to varia- tions of the magnetic strength and distortion will result. — wire having a large number of turns, the two coils being con- nected in series, as shown in fig. 7,370. The speaker is connected as indicated…",
    tags: ["audel-electric"],
  },
  {
    slug: "autobiography",
    title: "Autobiography",
    author: "John Stuart Mill",
    genre: "biography",
    genreLabel: "Biography",
    chunks: 1084,
    excerpt: "The _Traité de Legislation_ wound up with what was to me a most impressive picture of human life as it would be made by such opinions and such laws as were recommended in the treatise. The anticipations of practicable improvement were studiously moderate, deprecating and…",
    tags: ["biography"],
  },
  {
    slug: "autobiography_of_benjamin_franklin",
    title: "Autobiography of Benjamin Franklin",
    author: "Benjamin Franklin",
    genre: "biography",
    genreLabel: "Biography",
    chunks: 903,
    excerpt: "He lik'd it, but ask'd me if my being on the spot in England to chuse the types, and see that every thing was good of the kind, might not be of some advantage. \"Then,\" says he, \"when there, you may make acquaintances, and establish correspondences in the bookselling and…",
    tags: ["biography"],
  },
  {
    slug: "autobiography_of_benvenuto_cellini",
    title: "Autobiography of Benvenuto Cellini",
    author: "Benvenuto Cellini",
    genre: "biography",
    genreLabel: "Biography",
    chunks: 2480,
    excerpt: "The words of that great man so heartened me, that I set myself to work at once with eagerness upon the model; and when I had finished it, a painter who was intimate with Michel Agnolo, called Giuliano Bugiardini, brought me the drawing of Atlas. [2] On the same occasion I…",
    tags: ["biography"],
  },
  {
    slug: "confessions_jean_jacques_rousseau",
    title: "Confessions — Jean-Jacques Rousseau",
    author: "Jean-Jacques Rousseau",
    genre: "biography",
    genreLabel: "Biography",
    chunks: 3792,
    excerpt: "I know not what I should have said to her; but her friend entered, and at that moment I thought her ugly. At length, they bethought themselves, that they must return to town before night; even now we had but just time to reach it by daylight; and we hastened our departure in…",
    tags: ["biography"],
  },
  {
    slug: "confessions_saint_augustine",
    title: "Confessions — Saint Augustine",
    author: "of Hippo, Saint Augustine",
    genre: "biography",
    genreLabel: "Biography",
    chunks: 1448,
    excerpt: "For as deeds of violence arise, if that emotion of the soul be corrupted, whence vehement action springs, stirring itself insolently and unrulily; and lusts, when that affection of the soul is ungoverned, whereby carnal pleasures are drunk in, so do errors and false opinions…",
    tags: ["biography"],
  },
  {
    slug: "incidents_in_the_life_of_a_slave_girl_harriet_jacobs",
    title: "Incidents in the Life of a Slave Girl — Harriet Jacobs",
    author: "Harriet A. (Harriet Ann) Jacobs",
    genre: "biography",
    genreLabel: "Biography",
    chunks: 1035,
    excerpt: "She had not forgotten poor Benjamin’s sufferings, and she was afraid that if another child tried to escape, he would have a similar or a worse fate. To me, nothing seemed more dreadful than my present life. I said to myself, “William _must_ be free. He shall go to the north,…",
    tags: ["biography"],
  },
  {
    slug: "narrative_of_the_life_of_frederick_douglass",
    title: "Narrative of the Life of Frederick Douglass",
    author: "Frederick Douglass",
    genre: "biography",
    genreLabel: "Biography",
    chunks: 524,
    excerpt: "The slaves selected to go to the Great House Farm, for the monthly allowance for themselves and their fellow-slaves, were peculiarly enthusiastic. While on their way, they would make the dense old woods, for miles around, reverberate with their wild songs, revealing at once…",
    tags: ["biography"],
  },
  {
    slug: "personal_memoirs_of_ulysses_s_grant_volume_1",
    title: "Personal Memoirs of Ulysses S. Grant — Volume 1",
    author: "Ulysses S. (Ulysses Simpson) Grant",
    genre: "biography",
    genreLabel: "Biography",
    chunks: 3770,
    excerpt: "He was a brave and very earnest soldier. No man in the service was more sincere in his devotion to the cause for which we were battling; none more ready to make sacrifices or risk life in it. On the 4th of September I removed my headquarters to Cairo and found Colonel Richard…",
    tags: ["biography"],
  },
  {
    slug: "the_education_of_henry_adams",
    title: "The Education of Henry Adams",
    author: "Henry Adams",
    genre: "biography",
    genreLabel: "Biography",
    chunks: 2489,
    excerpt: "His friends were good to him. Life was amusing. Paris rapidly became familiar. In a month or six weeks he forgot even to disapprove of it; but he studied nothing, entered no society, and made no acquaintance.",
    tags: ["biography"],
  },
  {
    slug: "the_life_of_samuel_johnson_james_boswell",
    title: "The Life of Samuel Johnson — James Boswell",
    author: "James Boswell",
    genre: "biography",
    genreLabel: "Biography",
    chunks: 2932,
    excerpt: "He said, 'Sir, I make a distinction between what a man may experience by the mere strength of his imagination, and what imagination cannot possibly produce. Thus, suppose I should think that I saw a form, and heard a voice cry \"Johnson, you are a very wicked fellow, and…",
    tags: ["biography"],
  },
  {
    slug: "up_from_slavery_booker_t_washington",
    title: "Up From Slavery — Booker T. Washington",
    author: "Booker T. Washington",
    genre: "biography",
    genreLabel: "Biography",
    chunks: 1018,
    excerpt: "Take the broom and sweep it.” It occurred to me at once that here was my chance. Never did I receive an order with more delight. I knew that I could sweep, for Mrs. Ruffner had thoroughly taught me how to do that when I lived with her. I swept the recitation-room three times.…",
    tags: ["biography"],
  },
  {
    slug: "miracle_mongers_and_their_methods",
    title: "Miracle Mongers and Their Methods",
    author: "Unknown",
    genre: "curiosities",
    genreLabel: "Curiosities",
    chunks: 579,
    excerpt: "Girardelli FROM THE CONTINENT, * Iwtfj wm I ih* rtwltrsf *** buMtbi bo nor «f tpptanfv* before m«i of A« Ciuioul Uadi of Eutopr, who npwd the bif beat iiiWirtjua aod uioakhaint it her wo&derfid Pfrformio.ff t tad *lw «i tlx Tbetlra R*y*V J^sJdd, fiih uiimul ippkiM Her Powers…",
    tags: ["curiosities"],
  },
  {
    slug: "the_diary_of_john_evelyn_volume_1",
    title: "The Diary of John Evelyn — Volume 1",
    author: "John Evelyn",
    genre: "diaries",
    genreLabel: "Diaries",
    chunks: 3156,
    excerpt: "We embarked in a felucca for Livorno, or Leghorn; but the sea running very high, we put in at Porto Venere, which we made with peril, between two narrow horrid rocks, against which the sea dashed with great velocity; but we were soon delivered into as great a calm and a most…",
    tags: ["diaries"],
  },
  {
    slug: "the_diary_of_john_evelyn_volume_2",
    title: "The Diary of John Evelyn — Volume 2",
    author: "John Evelyn",
    genre: "diaries",
    genreLabel: "Diaries",
    chunks: 2943,
    excerpt: "Lord Ossory several times deplored to me his being engaged in it; he had more justice and honor than in the least to approve of it, though he had been over-persuaded to the expedition.",
    tags: ["diaries"],
  },
  {
    slug: "the_diary_of_samuel_pepys_complete",
    title: "The Diary of Samuel Pepys — Complete",
    author: "Samuel Pepys",
    genre: "diaries",
    genreLabel: "Diaries",
    chunks: 18517,
    excerpt: "He also told me that he heard that exceptions were taken at his carrying his wife down to Portsmouth, saying that the King should not pay for it, but I denied that I had spoke of it, nor did I. At last he desired the difference between our wives might not make a difference…",
    tags: ["diaries"],
  },
  {
    slug: "the_journal_of_a_tour_to_the_hebrides_with_samuel_johnson",
    title: "The Journal of a Tour to the Hebrides with Samuel Johnson",
    author: "James Boswell",
    genre: "diaries",
    genreLabel: "Diaries",
    chunks: 2826,
    excerpt: "That stone was the capital one of the circle which surrounded what now remains. Mr Fraser was very hospitable. There was a fair at Strichen; and he had several of his neighbours from it at dinner.",
    tags: ["diaries"],
  },
  {
    slug: "a_dolls_house_henrik_ibsen",
    title: "A Doll's House — Henrik Ibsen",
    author: "Henrik Ibsen",
    genre: "drama",
    genreLabel: "Drama",
    chunks: 328,
    excerpt: "NORA. Be so good as to go into the study, then. _[She bows indifferently to him and shuts the door into the hall; then comes back and makes up the fire in the stove.]_ MRS LINDE. Nora—who was that man? NORA. A lawyer, of the name of Krogstad. MRS LINDE. Then it really was he.…",
    tags: ["drama"],
  },
  {
    slug: "doctor_faustus_christopher_marlowe",
    title: "Doctor Faustus — Christopher Marlowe",
    author: "Christopher Marlowe",
    genre: "drama",
    genreLabel: "Drama",
    chunks: 277,
    excerpt: "FAUSTUS. Already Faustus hath hazarded that for thee. MEPHIST. But, Faustus, thou must bequeath it solemnly, And write a deed of gift with thine own blood; For that security craves great Lucifer. If thou deny it, I will back to hell. FAUSTUS. Stay, Mephistophilis, and tell…",
    tags: ["drama"],
  },
  {
    slug: "hedda_gabler_henrik_ibsen",
    title: "Hedda Gabler — Henrik Ibsen",
    author: "Henrik Ibsen",
    genre: "drama",
    genreLabel: "Drama",
    chunks: 391,
    excerpt: "MISS TESMAN. Yes, don't be uneasy, my dear boy.--Besides, I have given security for the furniture and all the carpets. TESMAN. Security? You? My dear Aunt Julia--what sort of security could you give? MISS TESMAN. I have given a mortgage on our annuity. TESMAN. [Jumps up.]…",
    tags: ["drama"],
  },
  {
    slug: "major_barbara",
    title: "Major Barbara",
    author: "Bernard Shaw",
    genre: "drama",
    genreLabel: "Drama",
    chunks: 422,
    excerpt: "UNDERSHAFT. Well, I will make a bargain with you. If I go to see you to-morrow in your Salvation Shelter, will you come the day after to see me in my cannon works? BARBARA. Take care. It may end in your giving up the cannons for the sake of the Salvation Army. UNDERSHAFT. Are…",
    tags: ["drama"],
  },
  {
    slug: "pygmalion_george_bernard_shaw",
    title: "Pygmalion — George Bernard Shaw",
    author: "Bernard Shaw",
    genre: "drama",
    genreLabel: "Drama",
    chunks: 441,
    excerpt: "Well, you wouldn’t have the face to ask me the same for teaching me my own language as you would for French; so I won’t give more than a shilling. Take it or leave it. HIGGINS [walking up and down the room, rattling his keys and his cash in his pockets] You know, Pickering,…",
    tags: ["drama"],
  },
  {
    slug: "tamburlaine_the_great_christopher_marlowe",
    title: "Tamburlaine the Great — Christopher Marlowe",
    author: "Christopher Marlowe",
    genre: "drama",
    genreLabel: "Drama",
    chunks: 359,
    excerpt: "USUMCASANE. Long may Theridamas remain with us! TAMBURLAINE. These are my friends, in whom I more rejoice Than doth the king of Persia in his crown; And, by the love of Pylades and Orestes, Whose statues [61] we adore in Scythia, Thyself and them shall never part from me…",
    tags: ["drama"],
  },
  {
    slug: "the_duchess_of_malfi_john_webster",
    title: "The Duchess of Malfi — John Webster",
    author: "John Webster",
    genre: "drama",
    genreLabel: "Drama",
    chunks: 355,
    excerpt: "[Enter] BOSOLA and CASTRUCCIO BOSOLA. You say you would fain be taken for an eminent courtier? CASTRUCCIO. 'Tis the very main[31] of my ambition. BOSOLA. Let me see: you have a reasonable good face for 't already, and your night-cap expresses your ears sufficient largely. I…",
    tags: ["drama"],
  },
  {
    slug: "the_importance_of_being_earnest_oscar_wilde",
    title: "The Importance of Being Earnest — Oscar Wilde",
    author: "Oscar Wilde",
    genre: "drama",
    genreLabel: "Drama",
    chunks: 271,
    excerpt: "But I’ll run over the programme I’ve drawn out, if you will kindly come into the next room for a moment. LADY BRACKNELL. Thank you, Algernon. It is very thoughtful of you. [Rising, and following Algernon.] I’m sure the programme will be delightful, after a few expurgations.…",
    tags: ["drama"],
  },
  {
    slug: "the_master_builder",
    title: "The Master Builder",
    author: "Henrik Ibsen",
    genre: "drama",
    genreLabel: "Drama",
    chunks: 367,
    excerpt: "Then BROVIK comes into the front room. BROVIK. May I have a few words with you? SOLNESS. Certainly. BROVIK. [To KAIA.] Just go in there for moment, Kaia. KAIA. [Uneasily.] Oh, but uncle-- BROVIK. Do as I say, child. And shut the door after you. [KAIA goes reluctantly into the…",
    tags: ["drama"],
  },
  {
    slug: "the_sea_gull",
    title: "The sea-gull",
    author: "Anton Pavlovich Chekhov",
    genre: "drama",
    genreLabel: "Drama",
    chunks: 238,
    excerpt: "I, the spirit of the universe, I alone am immutable and eternal. [A pause] Like a captive in a dungeon deep and void, I know not where I am, nor what awaits me. One thing only is not hidden from me: in my fierce and obstinate battle with Satan, the source of the forces of…",
    tags: ["drama"],
  },
  {
    slug: "a_christmas_carol_in_prose_being_a_ghost_story_of_christmas",
    title: "A Christmas Carol in Prose; Being a Ghost Story of Christmas",
    author: "Charles Dickens",
    genre: "english-literature",
    genreLabel: "English Literature",
    chunks: 385,
    excerpt: "Not to know that any Christian spirit working kindly in its little sphere, whatever it may be, will find its mortal life too short for its vast means of usefulness. Not to know that no space of regret can make amends for one life's opportunity misused! Yet such was I! Oh!…",
    tags: ["english-literature"],
  },
  {
    slug: "a_modest_proposal",
    title: "A Modest Proposal",
    author: "Jonathan Swift",
    genre: "english-literature",
    genreLabel: "English Literature",
    chunks: 52,
    excerpt: "For we can neither employ them in handicraft or agriculture; they neither build houses, (I mean in the country) nor cultivate land: they can very seldom pick up a livelihood by stealing till they arrive at six years old; except where they are of towardly parts, although I…",
    tags: ["english-literature"],
  },
  {
    slug: "a_room_with_a_view_forster",
    title: "A Room with a View (Forster)",
    author: "E. M. (Edward Morgan) Forster",
    genre: "english-literature",
    genreLabel: "English Literature",
    chunks: 908,
    excerpt: "I must have dropped them out there in the square.” She looked at him cautiously. “Would you add to your kindness by fetching them?” He added to his kindness. As soon as he had turned his back, Lucy arose with the running of a maniac and stole down the arcade towards the Arno.…",
    tags: ["english-literature"],
  },
  {
    slug: "a_tale_of_two_cities",
    title: "A Tale of Two Cities",
    author: "Charles Dickens",
    genre: "english-literature",
    genreLabel: "English Literature",
    chunks: 1854,
    excerpt: "Lorry said it; perhaps not quite disinterestedly, but with the interested object of squeezing himself back again. “You think so?” said Mr. Stryver. “Well! you have been present all day, and you ought to know. You are a man of business, too.” “And as such,” quoth Mr. Lorry,…",
    tags: ["english-literature"],
  },
  {
    slug: "alices_adventures_in_wonderland",
    title: "Alices Adventures in Wonderland",
    author: "Lewis Carroll",
    genre: "english-literature",
    genreLabel: "English Literature",
    chunks: 309,
    excerpt: "However, when they had been running half an hour or so, and were quite dry again, the Dodo suddenly called out “The race is over!” and they all crowded round it, panting, and asking, “But who has won?” This question the Dodo could not answer without a great deal of thought,…",
    tags: ["english-literature"],
  },
  {
    slug: "bleak_house_dickens",
    title: "Bleak House (Dickens)",
    author: "Charles Dickens",
    genre: "english-literature",
    genreLabel: "English Literature",
    chunks: 4728,
    excerpt: "Then I felt I could not do it. Sometimes I considered whether I should write to his mother, but that ended in my being convinced that to open a correspondence would be to make the matter worse. I always came to the conclusion, finally, that I could do nothing. Mr.",
    tags: ["english-literature"],
  },
];
