import type { Book } from "./catalogTypes";

export const BOOKS_PART6: Book[] = [
  {
    slug: "dhammapada_f_max_müller_translation",
    title: "Dhammapada (F. Max Müller translation)",
    author: "Unknown",
    genre: "sacred-texts",
    genreLabel: "Sacred Texts",
    chunks: 166,
    excerpt: "Few are there among men who arrive at the other shore (become Arhats); the other people here run up and down the shore. 86. But those who, when the law has been well preached to them, follow the law, will pass across the dominion of death, however difficult to overcome. 87,…",
    tags: ["sacred-texts"],
  },
  {
    slug: "tao_te_ching_james_legge_translation",
    title: "Tao Te Ching (James Legge translation)",
    author: "Laozi",
    genre: "sacred-texts",
    genreLabel: "Sacred Texts",
    chunks: 142,
    excerpt: "The skilful masters (of the Tao) in old times, with a subtle and exquisite penetration, comprehended its mysteries, and were deep (also) so as to elude men's knowledge. As they were thus beyond men's knowledge, I will make an effort to describe of what sort they appeared to…",
    tags: ["sacred-texts"],
  },
  {
    slug: "the_analects_of_confucius_james_legge_translation",
    title: "The Analects of Confucius (James Legge translation)",
    author: "James Legge",
    genre: "sacred-texts",
    genreLabel: "Sacred Texts",
    chunks: 452,
    excerpt: "The acquaintance might be long, but he showed the same respect as at first.' CHAP. XVII. The Master said, 'Tsang Wan kept a large tortoise in a house, on the capitals of the pillars of which he had hills made, and with representations of duckweed on the small pillars above…",
    tags: ["sacred-texts"],
  },
  {
    slug: "the_bhagavad_gita_edwin_arnold_verse_translation",
    title: "The Bhagavad Gita (Edwin Arnold verse translation)",
    author: "Unknown",
    genre: "sacred-texts",
    genreLabel: "Sacred Texts",
    chunks: 287,
    excerpt: "Arjuna. Thou whom all mortals praise, Janardana! If meditation be a nobler thing Than action, wherefore, then, great Kesava! Dost thou impel me to this dreadful fight? Now am I by thy doubtful speech disturbed! Tell me one thing, and tell me certainly; By what road shall I…",
    tags: ["sacred-texts"],
  },
  {
    slug: "the_bible",
    title: "The Bible",
    author: "Unknown",
    genre: "sacred-texts",
    genreLabel: "Sacred Texts",
    chunks: 6654,
    excerpt: "Now after the death of Joshua it came to pass, that the children of Israel asked the LORD, saying, Who shall go up for us against the Canaanites first, to fight against them? 1:2 And the LORD said, Judah shall go up: behold, I have delivered the land into his hand. And Judah…",
    tags: ["sacred-texts"],
  },
  {
    slug: "the_quran_rodwell_translation",
    title: "The Quran (Rodwell translation)",
    author: "Unknown",
    genre: "sacred-texts",
    genreLabel: "Sacred Texts",
    chunks: 2648,
    excerpt: "He said to his nobles around him. \"This truly is a right cunning sorcerer: Fain would he drive you out of your land by his Sorcery.",
    tags: ["sacred-texts"],
  },
  {
    slug: "the_upanishads_max_müller_translation",
    title: "The Upanishads (Max Müller translation)",
    author: "Unknown",
    genre: "sacred-texts",
    genreLabel: "Sacred Texts",
    chunks: 284,
    excerpt: "They fall into blind darkness who worship the Unmanifested and they fall into greater darkness who worship the manifested.",
    tags: ["sacred-texts"],
  },
  {
    slug: "a_journey_in_other_worlds_a_romance_of_the_future",
    title: "A Journey in Other Worlds: A Romance of the Future",
    author: "John Jacob Astor",
    genre: "science-fiction",
    genreLabel: "Science Fiction",
    chunks: 1280,
    excerpt: "I expect to find it in its Palaeozoic or Mesozoic period, while over a hundred years ago the English astronomer, Chambers, thought that on Saturn there was good reason for suspecting the presence of snow.\" \"What sort of spaceship do you propose to have?\" asked the vice-president.",
    tags: ["science-fiction"],
  },
  {
    slug: "a_princess_of_mars",
    title: "A princess of Mars",
    author: "Edgar Rice Burroughs",
    genre: "science-fiction",
    genreLabel: "Science Fiction",
    chunks: 901,
    excerpt: "She, on the contrary, was sober with apparent solicitude and, as soon as I had finished the monster, rushed to me and carefully examined my body for possible wounds or injuries. Satisfying herself that I had come off unscathed she smiled quietly, and, taking my hand, started…",
    tags: ["science-fiction"],
  },
  {
    slug: "at_the_earths_core",
    title: "At the Earth's Core",
    author: "Edgar Rice Burroughs",
    genre: "science-fiction",
    genreLabel: "Science Fiction",
    chunks: 646,
    excerpt: "Their arms and necks were encircled by many ornaments of metal—silver predominating—and on their tunics were sewn the heads of tiny reptiles in odd and rather artistic designs. They talked among themselves as they marched along on either side of us, but in a language which I…",
    tags: ["science-fiction"],
  },
  {
    slug: "etidorhpa_or_the_end_of_earth",
    title: "Etidorhpa; or, The End of Earth.",
    author: "John Uri Lloyd",
    genre: "science-fiction",
    genreLabel: "Science Fiction",
    chunks: 1703,
    excerpt: "To the people of this State, and to your home, and kindred, you must become a stranger for all time. Do you consent?\" \"Yes,\" I answered, for I knew that I must acquiesce. \"In the next place, you must help us to remove all traces of your identity. You must, so far as the world…",
    tags: ["science-fiction"],
  },
  {
    slug: "flatland_a_romance_of_many_dimensions",
    title: "Flatland: A Romance of Many Dimensions",
    author: "Edwin Abbott Abbott",
    genre: "science-fiction",
    genreLabel: "Science Fiction",
    chunks: 488,
    excerpt: "The answer is threefold. The first means of recognition is the sense of hearing; which with us is far more highly developed than with you, and which enables us not only to distinguish by the voice our personal friends, but even to discriminate between different classes, at…",
    tags: ["science-fiction"],
  },
  {
    slug: "frankenstein",
    title: "Frankenstein",
    author: "Mary Wollstonecraft Shelley",
    genre: "science-fiction",
    genreLabel: "Science Fiction",
    chunks: 1022,
    excerpt: "If this rule were always observed; if no man allowed any pursuit whatsoever to interfere with the tranquillity of his domestic affections, Greece had not been enslaved, Cæsar would have spared his country, America would have been discovered more gradually, and the empires of…",
    tags: ["science-fiction"],
  },
  {
    slug: "pellucidar_burroughs",
    title: "Pellucidar (Burroughs)",
    author: "Edgar Rice Burroughs",
    genre: "science-fiction",
    genreLabel: "Science Fiction",
    chunks: 745,
    excerpt: "Below the water-line she was practically non-existent. She should have had considerable draft; but, as the enemy couldn’t have seen it, Perry decided to do away with it, and so made her flat-bottomed. It was this that caused my doubts about her. There was another little…",
    tags: ["science-fiction"],
  },
  {
    slug: "symzonia_voyage_of_discovery",
    title: "Symzonia: Voyage of Discovery",
    author: "Adam, Captain Seaborn",
    genre: "science-fiction",
    genreLabel: "Science Fiction",
    chunks: 627,
    excerpt: "I would not put up with it; there is but one Slim in the ship, and we'll heave him overboard, if you say the word; at least, I'd clap the ruffles [1] on him, and keep him out of harm's way the rest of the voyage.\" Whether it was honest indignation that prompted Will's advice,…",
    tags: ["science-fiction"],
  },
  {
    slug: "the_coming_race",
    title: "The Coming Race",
    author: "Edward Bulwer Lytton, Baron Lytton",
    genre: "science-fiction",
    genreLabel: "Science Fiction",
    chunks: 721,
    excerpt: "As these effects became familiarly known and skillfully administered, war between the vril-discoverers ceased, for they brought the art of destruction to such perfection as to annul all superiority in numbers, discipline, or military skill. The fire lodged in the hollow of a…",
    tags: ["science-fiction"],
  },
  {
    slug: "the_first_men_in_the_moon",
    title: "The First Men in the Moon",
    author: "H. G. (Herbert George) Wells",
    genre: "science-fiction",
    genreLabel: "Science Fiction",
    chunks: 919,
    excerpt: "So slight were the exertions required of us, so easy did the practical annihilation of our weight make all we had to do, that the necessity for taking refreshment did not occur to us for nearly six hours (by Cavor’s chronometer) after our start. I was amazed at that lapse of…",
    tags: ["science-fiction"],
  },
  {
    slug: "the_food_of_the_gods_and_how_it_came_to_earth",
    title: "The Food of the Gods and How It Came to Earth",
    author: "H. G. (Herbert George) Wells",
    genre: "science-fiction",
    genreLabel: "Science Fiction",
    chunks: 1028,
    excerpt: "\"It's too much to hope,\" said Bensington, \"that one of the wasps--\" \"The wasp has no more idea of public utility than a--than a House Agent,\" said Redwood.",
    tags: ["science-fiction"],
  },
  {
    slug: "the_gods_of_mars",
    title: "The Gods of Mars",
    author: "Edgar Rice Burroughs",
    genre: "science-fiction",
    genreLabel: "Science Fiction",
    chunks: 1065,
    excerpt: "I have spoken.” “Come, then,” I cried, “we must make the start, for we could not be further from escape than we now are in the heart of this mountain and within the four walls of this chamber of death.” “Come, then,” said the girl, “but do not flatter yourself that you can…",
    tags: ["science-fiction"],
  },
  {
    slug: "the_invisible_man",
    title: "The Invisible Man",
    author: "H. G. (Herbert George) Wells",
    genre: "science-fiction",
    genreLabel: "Science Fiction",
    chunks: 661,
    excerpt: "The bed-clothes gathered themselves together, leapt up suddenly into a sort of peak, and then jumped headlong over the bottom rail. It was exactly as if a hand had clutched them in the centre and flung them aside. Immediately after, the stranger’s hat hopped off the bed-post,…",
    tags: ["science-fiction"],
  },
  {
    slug: "the_lost_world",
    title: "The Lost World",
    author: "Arthur Conan Doyle",
    genre: "science-fiction",
    genreLabel: "Science Fiction",
    chunks: 1002,
    excerpt: "But the incident was far from being closed. Whatever path the lecturer took amid the wilds of the past seemed invariably to lead him to some assertion as to extinct or prehistoric life which instantly brought the same bulls' bellow from the Professor. The audience began to…",
    tags: ["science-fiction"],
  },
  {
    slug: "the_island_of_doctor_moreau",
    title: "The island of Doctor Moreau",
    author: "H. G. (Herbert George) Wells",
    genre: "science-fiction",
    genreLabel: "Science Fiction",
    chunks: 582,
    excerpt: "The reader will perhaps understand that at first everything was so strange about me, and my position was the outcome of such unexpected adventures, that I had no discernment of the relative strangeness of this or that thing. I followed the llama up the beach, and was…",
    tags: ["science-fiction"],
  },
  {
    slug: "the_warlord_of_mars",
    title: "The warlord of Mars",
    author: "Edgar Rice Burroughs",
    genre: "science-fiction",
    genreLabel: "Science Fiction",
    chunks: 768,
    excerpt: "And well it was that I had been forced to follow him. But a short distance from the circular chamber we came suddenly into a brilliantly lighted labyrinth of crystal glass partitioned passages. At first I thought it was one vast, unbroken chamber, so clear and transparent…",
    tags: ["science-fiction"],
  },
  {
    slug: "a_midsummer_nights_dream",
    title: "A Midsummer Nights Dream",
    author: "William Shakespeare",
    genre: "shakespeare",
    genreLabel: "Shakespeare",
    chunks: 233,
    excerpt: "Are not you he? PUCK. Thou speak’st aright; I am that merry wanderer of the night. I jest to Oberon, and make him smile, When I a fat and bean-fed horse beguile, Neighing in likeness of a filly foal; And sometime lurk I in a gossip’s bowl In very likeness of a roasted crab,…",
    tags: ["shakespeare"],
  },
  {
    slug: "hamlet",
    title: "Hamlet",
    author: "William Shakespeare",
    genre: "shakespeare",
    genreLabel: "Shakespeare",
    chunks: 420,
    excerpt: "Remember thee? Yea, from the table of my memory I’ll wipe away all trivial fond records, All saws of books, all forms, all pressures past, That youth and observation copied there; And thy commandment all alone shall live Within the book and volume of my brain, Unmix’d with…",
    tags: ["shakespeare"],
  },
  {
    slug: "macbeth",
    title: "Macbeth",
    author: "William Shakespeare",
    genre: "shakespeare",
    genreLabel: "Shakespeare",
    chunks: 249,
    excerpt: "But in these cases We still have judgement here; that we but teach Bloody instructions, which being taught, return To plague th’ inventor. This even-handed justice Commends th’ ingredience of our poison’d chalice To our own lips. He’s here in double trust: First, as I am his…",
    tags: ["shakespeare"],
  },
  {
    slug: "romeo_and_juliet",
    title: "Romeo and Juliet",
    author: "William Shakespeare",
    genre: "shakespeare",
    genreLabel: "Shakespeare",
    chunks: 340,
    excerpt: "MERCUTIO. O, then, I see Queen Mab hath been with you. She is the fairies’ midwife, and she comes In shape no bigger than an agate-stone On the fore-finger of an alderman, Drawn with a team of little atomies Over men’s noses as they lie asleep: Her waggon-spokes made of long…",
    tags: ["shakespeare"],
  },
  {
    slug: "don_quixote",
    title: "Don Quixote",
    author: "Miguel de Cervantes Saavedra",
    genre: "spanish",
    genreLabel: "Spanish Literature",
    chunks: 4032,
    excerpt: "Meanwhile the knight has taken his departure; he fights in the war, conquers the king’s enemy, wins many cities, triumphs in many battles, returns to the court, sees his lady where he was wont to see her, and it is agreed that he shall demand her in marriage of her parents as…",
    tags: ["spanish"],
  },
  {
    slug: "a_ladys_life_in_the_rocky_mountains",
    title: "A Lady's Life in the Rocky Mountains",
    author: "Isabella L. (Isabella Lucy) Bird",
    genre: "travel",
    genreLabel: "Travel",
    chunks: 1007,
    excerpt: "Holland says of another:-- If ever I shall reach the home in heaven, For whose dear rest I humbly hope and pray, In the great company of the forgiven I shall be sure to meet old Daniel Gray. The night came without coolness, but at daylight on Monday morning a fire was…",
    tags: ["travel"],
  },
  {
    slug: "the_innocents_abroad_mark_twain",
    title: "The Innocents Abroad — Mark Twain",
    author: "Mark Twain",
    genre: "travel",
    genreLabel: "Travel",
    chunks: 2582,
    excerpt: "I have not a word to say against the misused, faithful girl, and would not withhold from her grave a single one of those simple tributes which blighted youths and maidens offer to her memory, but I am sorry enough that I have not time and opportunity to write four or five…",
    tags: ["travel"],
  },
  {
    slug: "the_travels_of_marco_polo",
    title: "The Travels of Marco Polo",
    author: "da Pisa Rusticiano",
    genre: "travel",
    genreLabel: "Travel",
    chunks: 4983,
    excerpt: "But there is nothing particular to mention on the way till you come, at the end of those five days, to TADINFU.{1} This, you must know, is a very great city, and in old times was the seat of a great kingdom; but the Great Kaan conquered it by force of arms. Nevertheless it is…",
    tags: ["travel"],
  },
  {
    slug: "travels_in_the_interior_districts_of_africa_performed_under_",
    title: "Travels in the interior districts of Africa: performed under the direction and patronage of the African Association, in the years 1795, 1796, and 1797",
    author: "Mungo Park",
    genre: "travel",
    genreLabel: "Travel",
    chunks: 1995,
    excerpt: "In this pursuit I had wandered a little from my people, and being uncertain whether they were before or behind me, I hastened to a rising ground to look about me. As I was proceeding towards this eminence, two Negro horsemen, armed with muskets, came galloping from among the…",
    tags: ["travel"],
  },
  {
    slug: "two_years_before_the_mast",
    title: "Two Years Before the Mast",
    author: "Richard Henry Dana",
    genre: "travel",
    genreLabel: "Travel",
    chunks: 2251,
    excerpt: "No Protestant has any civil rights, nor can he hold any property, or, indeed, remain more than a few weeks on shore, unless he belong to some vessel. Consequently, the Americans and English who intend to remain here become Catholics, to a man; the current phrase among them…",
    tags: ["travel"],
  },
  {
    slug: "typee_a_peep_at_polynesian_life_herman_melville",
    title: "Typee: A Peep at Polynesian Life — Herman Melville",
    author: "Herman Melville",
    genre: "travel",
    genreLabel: "Travel",
    chunks: 1609,
    excerpt: "My curiosity had been not a little raised with regard to the description of country we should meet on the other side of the mountains; and I had supposed, with Toby, that immediately on gaining the heights we should be enabled to view the large bays of Happar and Typee…",
    tags: ["travel"],
  },
  {
    slug: "gitanjali_tagore",
    title: "Gitanjali (Tagore)",
    author: "Rabindranath Tagore",
    genre: "world-literature",
    genreLabel: "World Literature",
    chunks: 179,
    excerpt: "My heart longs to join in thy song, but vainly struggles for a voice. I would speak, but speech breaks not into song, and I cry out baffled. Ah, thou hast made my heart captive in the endless meshes of thy music, my master! 4. Life of my life, I shall ever try to keep my body…",
    tags: ["world-literature"],
  },
  {
    slug: "one_thousand_and_one_nights_lane_translation",
    title: "One Thousand and One Nights (Lane translation)",
    author: "Andrew Lang",
    genre: "world-literature",
    genreLabel: "World Literature",
    chunks: 1457,
    excerpt: "Now when I had ended my story, I proceeded to show the genius how to apply it to himself. \"O genius,\" I said, \"you see that this Sultan was not content with merely forgiving the envious man for the attempt on his life; he heaped rewards and riches upon him.\" But the genius…",
    tags: ["world-literature"],
  },
  {
    slug: "the_divine_comedy_carys_translation",
    title: "The Divine Comedy (Cary's Translation)",
    author: "Dante Alighieri",
    genre: "world-literature",
    genreLabel: "World Literature",
    chunks: 1476,
    excerpt: "But onward now: For now doth Cain with fork of thorns confine On either hemisphere, touching the wave Beneath the towers of Seville. Yesternight The moon was round. Thou mayst remember well: For she good service did thee in the gloom Of the deep wood.” This said, both onward…",
    tags: ["world-literature"],
  },
  {
    slug: "the_divine_comedy_longfellows_translation",
    title: "The Divine Comedy (Longfellow's Translation)",
    author: "Dante Alighieri",
    genre: "world-literature",
    genreLabel: "World Literature",
    chunks: 1437,
    excerpt: "Sitteth Peschiera, fortress fair and strong, To front the Brescians and the Bergamasks, Where round about the bank descendeth lowest. There of necessity must fall whatever In bosom of Benaco cannot stay, And grows a river down through verdant pastures. Soon as the water doth…",
    tags: ["world-literature"],
  },
];
