/* GutenbergKG corpus — public-domain texts, grown as trees.
 * Regenerated by scripts/export_web_catalog.py from per-book graph.sqlite.
 */
export type { Book } from "./catalogTypes";
import type { Book } from "./catalogTypes";
import { BOOKS_PART1 } from "./catalogPart1";
import { BOOKS_PART2 } from "./catalogPart2";
import { BOOKS_PART3 } from "./catalogPart3";
import { BOOKS_PART4 } from "./catalogPart4";
import { BOOKS_PART5 } from "./catalogPart5";
import { BOOKS_PART6 } from "./catalogPart6";

export const BOOKS: Book[] = [
  ...BOOKS_PART1,
  ...BOOKS_PART2,
  ...BOOKS_PART3,
  ...BOOKS_PART4,
  ...BOOKS_PART5,
  ...BOOKS_PART6,
];

export const GENRE_ORDER = [...new Set(BOOKS.map((b) => b.genre))];

export function bookBySlug(slug: string): Book | undefined {
  return BOOKS.find((b) => b.slug === slug);
}
